// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CreateTaskFromMessagesRequest 选集下载创建任务请求。
 */
export class CreateTaskFromMessagesRequest {
    /**
     * VideoID 视频源 ID（video_repo.vr_id）
     */
    "vr_id": number;

    /**
     * VideoName 视频标题（下载页展示用）
     */
    "vr_name": string;

    /**
     * VideoCover 视频封面相对路径
     */
    "vr_cover": string;

    /**
     * ChannelID 频道 ID（TG peer_id，对应 dialog_id 与 DialogPeerID）
     */
    "channel_id": number;

    /**
     * Episodes 选中的分集列表
     */
    "episodes": EpisodeDownloadInput[];

    /**
     * VideoPrefix 视频文件名前缀（可空）
     */
    "video_prefix": string;

    /** Creates a new CreateTaskFromMessagesRequest instance. */
    constructor($$source: Partial<CreateTaskFromMessagesRequest> = {}) {
        if (!("vr_id" in $$source)) {
            this["vr_id"] = 0;
        }
        if (!("vr_name" in $$source)) {
            this["vr_name"] = "";
        }
        if (!("vr_cover" in $$source)) {
            this["vr_cover"] = "";
        }
        if (!("channel_id" in $$source)) {
            this["channel_id"] = 0;
        }
        if (!("episodes" in $$source)) {
            this["episodes"] = [];
        }
        if (!("video_prefix" in $$source)) {
            this["video_prefix"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTaskFromMessagesRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateTaskFromMessagesRequest {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("episodes" in $$parsedSource) {
            $$parsedSource["episodes"] = $$createField4_0($$parsedSource["episodes"]);
        }
        return new CreateTaskFromMessagesRequest($$parsedSource as Partial<CreateTaskFromMessagesRequest>);
    }
}

/**
 * DownloadRecord 单个文件的下载记录，对应 SQLite download_records 表的一行。
 */
export class DownloadRecord {
    /**
     * ID 记录自增主键
     */
    "id": number;

    /**
     * TaskID 所属任务 ID
     */
    "task_id": number;

    /**
     * MessageID 文件所属消息 ID
     */
    "message_id": number;

    /**
     * FileID 文件唯一标识（gotd Document.ID/Photo.ID 的字符串形式）
     */
    "file_id": string;

    /**
     * FileName 渲染后的最终文件名
     */
    "file_name": string;

    /**
     * FileSize 文件大小（字节）
     */
    "file_size": number;

    /**
     * MediaType 媒体类型：video/audio/photo/document
     */
    "media_type": string;

    /**
     * Status 下载状态：pending/downloading/completed/failed
     */
    "status": string;

    /**
     * LocalPath 本地保存路径（下载完成后填充）
     */
    "local_path": string;

    /**
     * Error 错误信息（status=failed 时填充）
     */
    "error": string;

    /**
     * CreatedAt 创建时间（RFC3339）
     */
    "created_at": string;

    /**
     * SortOrder 排序顺序（从 1 开始；按 sort_order ASC 控制下载顺序）
     * 扫描时按 message_id ASC 初始化；用户在前端确认排序后由 SortTaskRecords/ReorderTaskRecords 更新。
     */
    "sort_order": number;

    /**
     * EpisodeNumber 集数（由 EpisodeRegex 提取的 capture group 解析为整数；nil 表示未提取到）
     */
    "episode_number": number | null;

    /**
     * EpisodeRaw 集数 capture group 原始字符串（未解析为数字前的文本，便于前端展示与调试）
     */
    "episode_raw": string;

    /**
     * DownloadedBytes 已下载字节数（暂停时持久化，恢复时用于断点续传 seek 位置）
     */
    "downloaded_bytes": number;

    /**
     * RenderedName 按任务命名模板渲染后的最终文件名（不入库，仅 JSON 返回前端展示用）。
     * 在 ListRecordsByTask 后由 service 层根据 TaskConfig 渲染填充。
     * 注意：未做冲突解决（同名文件加 _1 _2 后缀），仅展示模板渲染结果。
     */
    "rendered_name": string;

    /** Creates a new DownloadRecord instance. */
    constructor($$source: Partial<DownloadRecord> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("task_id" in $$source)) {
            this["task_id"] = 0;
        }
        if (!("message_id" in $$source)) {
            this["message_id"] = 0;
        }
        if (!("file_id" in $$source)) {
            this["file_id"] = "";
        }
        if (!("file_name" in $$source)) {
            this["file_name"] = "";
        }
        if (!("file_size" in $$source)) {
            this["file_size"] = 0;
        }
        if (!("media_type" in $$source)) {
            this["media_type"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("local_path" in $$source)) {
            this["local_path"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("episode_number" in $$source)) {
            this["episode_number"] = null;
        }
        if (!("episode_raw" in $$source)) {
            this["episode_raw"] = "";
        }
        if (!("downloaded_bytes" in $$source)) {
            this["downloaded_bytes"] = 0;
        }
        if (!("rendered_name" in $$source)) {
            this["rendered_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadRecord($$parsedSource as Partial<DownloadRecord>);
    }
}

/**
 * EpisodeDownloadInput 选集下载输入项（由前端选集弹窗提交）。
 */
export class EpisodeDownloadInput {
    /**
     * MessageID 频道消息 ID
     */
    "message_id": number;

    /**
     * EpisodeNumber 集数（来自 video_episodes.ve_collect，0 表示未识别）
     */
    "episode_number": number;

    /**
     * Title 分集标题（来自 video_episodes.ve_title，可空）
     */
    "title": string;

    /** Creates a new EpisodeDownloadInput instance. */
    constructor($$source: Partial<EpisodeDownloadInput> = {}) {
        if (!("message_id" in $$source)) {
            this["message_id"] = 0;
        }
        if (!("episode_number" in $$source)) {
            this["episode_number"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EpisodeDownloadInput instance from a string or object.
     */
    static createFrom($$source: any = {}): EpisodeDownloadInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EpisodeDownloadInput($$parsedSource as Partial<EpisodeDownloadInput>);
    }
}

/**
 * EpisodeDownloadStatus 分集下载状态项。
 * 用于选集弹窗展示每集是否已下载。
 */
export class EpisodeDownloadStatus {
    /**
     * MessageID 消息 ID
     */
    "message_id": number;

    /**
     * Status 下载状态：pending/downloading/completed/failed
     * 空字符串表示无下载记录（未下载）
     */
    "status": string;

    /** Creates a new EpisodeDownloadStatus instance. */
    constructor($$source: Partial<EpisodeDownloadStatus> = {}) {
        if (!("message_id" in $$source)) {
            this["message_id"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EpisodeDownloadStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): EpisodeDownloadStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EpisodeDownloadStatus($$parsedSource as Partial<EpisodeDownloadStatus>);
    }
}

/**
 * RecentMessage 表示一条频道最新消息的预览数据。
 * 用于前端"测试匹配"弹窗中展示消息列表，供用户复制文本、调整关键词。
 */
export class RecentMessage {
    /**
     * MessageID 消息 ID
     */
    "message_id": number;

    /**
     * MediaType 媒体类型：video/audio/photo/document/none
     * none 表示该消息无媒体文件（纯文本消息）
     */
    "media_type": string;

    /**
     * FileName 文件名（来自 DocumentAttributeFilename，无媒体或无文件名时为空）
     */
    "file_name": string;

    /**
     * FileSize 文件大小（字节，无媒体时为 0）
     */
    "file_size": number;

    /**
     * MessageText 消息文本内容（含 caption）
     */
    "message_text": string;

    /**
     * Date 消息日期（RFC3339）
     */
    "date": string;

    /**
     * HasMedia 是否含媒体文件
     */
    "has_media": boolean;

    /** Creates a new RecentMessage instance. */
    constructor($$source: Partial<RecentMessage> = {}) {
        if (!("message_id" in $$source)) {
            this["message_id"] = 0;
        }
        if (!("media_type" in $$source)) {
            this["media_type"] = "";
        }
        if (!("file_name" in $$source)) {
            this["file_name"] = "";
        }
        if (!("file_size" in $$source)) {
            this["file_size"] = 0;
        }
        if (!("message_text" in $$source)) {
            this["message_text"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("has_media" in $$source)) {
            this["has_media"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): RecentMessage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentMessage($$parsedSource as Partial<RecentMessage>);
    }
}

/**
 * SortBy 定义排序键。
 */
export enum SortBy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * SortByEpisode 按集数（episode_number）升序，未提取到集数的排在最后
     */
    SortByEpisode = "episode",

    /**
     * SortByMessageID 按 Telegram 消息 ID 升序（频道内发布顺序，最稳定）
     */
    SortByMessageID = "message_id",

    /**
     * SortByDate 按消息日期升序
     */
    SortByDate = "date",
};

/**
 * Subscription 表示对一个对话的实时监听订阅。
 * 每条订阅绑定一个 dialog（通过 DialogPeerID 唯一标识），并携带筛选条件与命名配置。
 */
export class Subscription {
    /**
     * ID 自增主键
     */
    "id": number;

    /**
     * DialogPeerID 对话对端 ID（频道/群组/用户 ID），唯一
     */
    "dialog_peer_id": number;

    /**
     * DialogAccessHash 访问哈希（频道/用户必填，群组为 0）
     */
    "dialog_access_hash": number;

    /**
     * DialogName 对话名称（用于下载目录命名）
     */
    "dialog_name": string;

    /**
     * MediaTypes 媒体类型筛选：video/audio/photo/document（为空表示不过滤）
     */
    "media_types": string[];

    /**
     * Keywords 关键词过滤（消息文本/caption 包含任一关键词则匹配；为空表示不过滤）
     */
    "keywords": string[];

    /**
     * VideoPrefix 视频文件名前缀
     */
    "video_prefix": string;

    /**
     * NamingTemplate 命名模板（参考 template.NamingVars 支持的变量）
     */
    "naming_template": string;

    /**
     * Enabled 是否启用监听
     */
    "enabled": boolean;

    /**
     * CreatedAt 创建时间（RFC3339）
     */
    "created_at": string;

    /**
     * UpdatedAt 更新时间（RFC3339）
     */
    "updated_at": string;

    /** Creates a new Subscription instance. */
    constructor($$source: Partial<Subscription> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("dialog_peer_id" in $$source)) {
            this["dialog_peer_id"] = 0;
        }
        if (!("dialog_access_hash" in $$source)) {
            this["dialog_access_hash"] = 0;
        }
        if (!("dialog_name" in $$source)) {
            this["dialog_name"] = "";
        }
        if (!("media_types" in $$source)) {
            this["media_types"] = [];
        }
        if (!("keywords" in $$source)) {
            this["keywords"] = [];
        }
        if (!("video_prefix" in $$source)) {
            this["video_prefix"] = "";
        }
        if (!("naming_template" in $$source)) {
            this["naming_template"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Subscription instance from a string or object.
     */
    static createFrom($$source: any = {}): Subscription {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("media_types" in $$parsedSource) {
            $$parsedSource["media_types"] = $$createField4_0($$parsedSource["media_types"]);
        }
        if ("keywords" in $$parsedSource) {
            $$parsedSource["keywords"] = $$createField5_0($$parsedSource["keywords"]);
        }
        return new Subscription($$parsedSource as Partial<Subscription>);
    }
}

/**
 * Task 下载任务模型，对应 SQLite tasks 表的一行。
 */
export class Task {
    /**
     * ID 任务自增主键
     */
    "id": number;

    /**
     * DialogID 频道/群组/用户 ID（与 TaskConfig.DialogPeerID 一致，单独冗余便于查询）
     */
    "dialog_id": number;

    /**
     * Status 当前任务状态
     */
    "status": TaskStatus;

    /**
     * ScanOffset 扫描位置（最新已扫描消息 ID），用于增量扫描
     */
    "scan_offset": number;

    /**
     * TotalFiles 匹配到的文件总数
     */
    "total_files": number;

    /**
     * CompletedFiles 已完成下载数
     */
    "completed_files": number;

    /**
     * FailedFiles 失败下载数
     */
    "failed_files": number;

    /**
     * Config 任务配置（JSON 序列化存储）
     */
    "config": TaskConfig;

    /**
     * CreatedAt 创建时间（RFC3339）
     */
    "created_at": string;

    /**
     * UpdatedAt 更新时间（RFC3339）
     */
    "updated_at": string;

    /**
     * VideoID 关联视频源 video_repo.vr_id（选集下载场景填充，0 表示扫描下载场景）
     */
    "vr_id": number;

    /**
     * VideoName 视频标题（下载页展示用，避免二次查询）
     */
    "vr_name": string;

    /**
     * VideoCover 视频封面相对路径（下载页展示用）
     */
    "vr_cover": string;

    /** Creates a new Task instance. */
    constructor($$source: Partial<Task> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("dialog_id" in $$source)) {
            this["dialog_id"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = TaskStatus.$zero;
        }
        if (!("scan_offset" in $$source)) {
            this["scan_offset"] = 0;
        }
        if (!("total_files" in $$source)) {
            this["total_files"] = 0;
        }
        if (!("completed_files" in $$source)) {
            this["completed_files"] = 0;
        }
        if (!("failed_files" in $$source)) {
            this["failed_files"] = 0;
        }
        if (!("config" in $$source)) {
            this["config"] = (new TaskConfig());
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("vr_id" in $$source)) {
            this["vr_id"] = 0;
        }
        if (!("vr_name" in $$source)) {
            this["vr_name"] = "";
        }
        if (!("vr_cover" in $$source)) {
            this["vr_cover"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     */
    static createFrom($$source: any = {}): Task {
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField7_0($$parsedSource["config"]);
        }
        return new Task($$parsedSource as Partial<Task>);
    }
}

/**
 * TaskConfig 任务配置。
 * 字段与 template.TaskTemplateConfig 一致，额外携带频道（对话）信息，
 * 用于在 SQLite 中以 JSON 字符串保存任务配置，便于任务恢复时直接还原。
 */
export class TaskConfig {
    /**
     * DialogPeerID 频道/群组/用户 ID
     */
    "dialog_peer_id": number;

    /**
     * DialogAccessHash 访问哈希（频道/用户必填，群组为 0）
     */
    "dialog_access_hash": number;

    /**
     * DialogName 频道/群组名称或用户姓名（仅用于前端展示，下载目录改用 SearchTerm）
     */
    "dialog_name": string;

    /**
     * MediaTypes 媒体类型筛选：video/audio/photo/document
     */
    "media_types": string[];

    /**
     * Keywords 关键词过滤（为空表示不过滤）
     */
    "keywords": string[];

    /**
     * SearchTerm 搜索词（可选）。传给 Telegram 服务器的 messages.search q 参数，让服务器在索引层预过滤。
     * 与 Keywords 的区别：
     *   - SearchTerm 是服务器端全文搜索（减少返回的消息总量），由 Telegram 服务器执行
     *   - Keywords 是客户端本地精筛（在 SearchTerm 预过滤后的结果上再做精确匹配）
     * 两者正交、可同时配置：先用 SearchTerm 缩小范围，再用 Keywords 精确匹配。
     * 留空表示不启用服务器搜索，按原有 MessagesGetHistory 流程扫描。
     */
    "search_term": string;

    /**
     * SaveDirName 保存目录名（必填）。作为该任务下载文件的存放目录名（位于下载根目录下）。
     * 经 Windows 非法字符净化后创建实际目录，使每个任务的文件按主题分目录存放。
     * 与 SearchTerm 解耦：SearchTerm 控制服务器搜索范围，SaveDirName 控制文件存放位置。
     */
    "save_dir_name": string;

    /**
     * KeywordMatchScope 关键词匹配范围：
     *   "filename" 仅匹配文件名
     *   "message"  仅匹配消息文本（含 caption）
     *   "both"     文件名或消息文本任一命中即匹配（默认）
     */
    "keyword_match_scope": string;

    /**
     * KeywordMatchMode 关键词命中数量模式：
     *   "any" 任意一个关键词命中即视为匹配（默认）
     *   "all" 所有关键词都必须命中才视为匹配
     * 与 KeywordMatchScope 正交：scope 控制“在哪里匹配”，mode 控制“匹配多少个”。
     */
    "keyword_match_mode": string;

    /**
     * EpisodeRegex 集数提取正则（Go RE2 语法，至少包含一个 capture group）。
     * 配置后扫描时会从文件名与消息内容中提取集数，用于后续排序与重命名。
     * 留空表示不启用集数提取，扫描完成按原有流程（auto_download 决定是否立即下载）。
     */
    "episode_regex": string;

    /**
     * RequireEpisodeMatch 是否要求集数正则必须命中。
     *   true  正则未命中的消息会被过滤（不创建下载记录）
     *   false 正则仅用于提取集数与排序，未命中的消息集数为 nil，排序时排在最后
     */
    "require_episode_match": boolean;

    /**
     * ScanFromNewest 是否从最新消息开始向前扫描。
     *   true  忽略历史 scan_offset，从最新消息开始向更旧方向翻页（适合"找最新分集"场景）
     *   false 复用历史 scan_offset 增量扫描（避免重复扫描已处理过的旧消息）
     * 默认 false（增量扫描）。
     */
    "scan_from_newest": boolean;

    /**
     * MaxMatches 最大匹配文件数量（0 表示不限制）。
     * 达到此数量后停止扫描。用于限制扫描范围、避免频道过大时拉取过多消息。
     * 注意：达到上限时已扫描到的所有匹配都会保留，不会截断。
     */
    "max_matches": number;

    /**
     * StopAtFirstEpisode 是否在遇到"集数 1"时停止扫描。
     * 仅当 EpisodeRegex 非空 + ScanFromNewest=true 时生效。
     * 用于"从最新往前找"场景：扫到第一季第一集（episode_number=1）时停止，
     * 假设再往前的消息已不是同一季内容。
     */
    "stop_at_first_episode": boolean;

    /**
     * VideoPrefix 视频文件名前缀
     */
    "video_prefix": string;

    /**
     * Concurrency 单任务内并发数（≤10）
     */
    "concurrency": number;

    /**
     * SpeedLimit 限速 bytes/s（0 表示不限）
     */
    "speed_limit": number;

    /**
     * NamingTemplate 命名模板（参考 template.NamingVars 支持的变量）
     */
    "naming_template": string;

    /**
     * AutoDownload 扫描完成后是否自动开始下载
     */
    "auto_download": boolean;

    /** Creates a new TaskConfig instance. */
    constructor($$source: Partial<TaskConfig> = {}) {
        if (!("dialog_peer_id" in $$source)) {
            this["dialog_peer_id"] = 0;
        }
        if (!("dialog_access_hash" in $$source)) {
            this["dialog_access_hash"] = 0;
        }
        if (!("dialog_name" in $$source)) {
            this["dialog_name"] = "";
        }
        if (!("media_types" in $$source)) {
            this["media_types"] = [];
        }
        if (!("keywords" in $$source)) {
            this["keywords"] = [];
        }
        if (!("search_term" in $$source)) {
            this["search_term"] = "";
        }
        if (!("save_dir_name" in $$source)) {
            this["save_dir_name"] = "";
        }
        if (!("keyword_match_scope" in $$source)) {
            this["keyword_match_scope"] = "";
        }
        if (!("keyword_match_mode" in $$source)) {
            this["keyword_match_mode"] = "";
        }
        if (!("episode_regex" in $$source)) {
            this["episode_regex"] = "";
        }
        if (!("require_episode_match" in $$source)) {
            this["require_episode_match"] = false;
        }
        if (!("scan_from_newest" in $$source)) {
            this["scan_from_newest"] = false;
        }
        if (!("max_matches" in $$source)) {
            this["max_matches"] = 0;
        }
        if (!("stop_at_first_episode" in $$source)) {
            this["stop_at_first_episode"] = false;
        }
        if (!("video_prefix" in $$source)) {
            this["video_prefix"] = "";
        }
        if (!("concurrency" in $$source)) {
            this["concurrency"] = 0;
        }
        if (!("speed_limit" in $$source)) {
            this["speed_limit"] = 0;
        }
        if (!("naming_template" in $$source)) {
            this["naming_template"] = "";
        }
        if (!("auto_download" in $$source)) {
            this["auto_download"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskConfig {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("media_types" in $$parsedSource) {
            $$parsedSource["media_types"] = $$createField3_0($$parsedSource["media_types"]);
        }
        if ("keywords" in $$parsedSource) {
            $$parsedSource["keywords"] = $$createField4_0($$parsedSource["keywords"]);
        }
        return new TaskConfig($$parsedSource as Partial<TaskConfig>);
    }
}

/**
 * TaskStatus 表示下载任务的状态。
 */
export enum TaskStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 任务状态常量。
     *
     * StatusScanning 扫描中：任务已创建，正在遍历频道历史消息匹配文件。
     */
    StatusScanning = "scanning",

    /**
     * StatusAwaitingSort 待排序：扫描已完成且配置了集数正则，
     * 需用户在前端确认排序后再手动开始下载（不自动进入下载状态）。
     */
    StatusAwaitingSort = "awaiting_sort",

    /**
     * StatusPending 待确认：扫描已完成，等待用户确认是否开始下载。
     */
    StatusPending = "pending",

    /**
     * StatusDownloading 进行中：任务正在下载匹配到的文件。
     */
    StatusDownloading = "downloading",

    /**
     * StatusPaused 已暂停：用户主动暂停，可恢复。
     */
    StatusPaused = "paused",

    /**
     * StatusCompleted 已完成：所有文件下载完成。
     */
    StatusCompleted = "completed",

    /**
     * StatusFailed 失败：任务执行过程中出现致命错误。
     */
    StatusFailed = "failed",
};

// Private type creation functions
const $$createType0 = EpisodeDownloadInput.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = TaskConfig.createFrom;
