// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DialogInfo 表示单个对话的元信息。
 * 该结构同时用于 API 返回与 SQLite 持久化（JSON 标签供前端直接消费）。
 */
export class DialogInfo {
    /**
     * 对话对端 ID（频道/群组/用户 ID）
     */
    "peer_id": number;

    /**
     * 访问哈希（频道/用户需要，群组为 0）
     */
    "access_hash": number;

    /**
     * 显示名称（频道/群组标题，或用户姓名）
     */
    "name": string;

    /**
     * 对话类型
     */
    "type": DialogType;

    /**
     * 最新消息 ID（top_message）
     */
    "last_message_id": number;

    /**
     * 频道/用户用户名（@xxx，可空）
     */
    "username": string;

    /**
     * 头像 file_id（暂存，不下载）
     */
    "avatar_file_id": string;

    /** Creates a new DialogInfo instance. */
    constructor($$source: Partial<DialogInfo> = {}) {
        if (!("peer_id" in $$source)) {
            this["peer_id"] = 0;
        }
        if (!("access_hash" in $$source)) {
            this["access_hash"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = DialogType.$zero;
        }
        if (!("last_message_id" in $$source)) {
            this["last_message_id"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("avatar_file_id" in $$source)) {
            this["avatar_file_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DialogInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DialogInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DialogInfo($$parsedSource as Partial<DialogInfo>);
    }
}

/**
 * DialogType 表示对话的类型。
 */
export enum DialogType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 支持的对话类型常量。
     *
     * DialogTypeChannel 表示频道（含超级群组）。
     */
    DialogTypeChannel = "channel",

    /**
     * DialogTypeChat 表示普通群组（basic group）。
     */
    DialogTypeChat = "chat",

    /**
     * DialogTypeUser 表示私聊用户。
     */
    DialogTypeUser = "user",
};

/**
 * LoginStep 表示当前登录流程所处的步骤。
 */
export enum LoginStep {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 支持的登录步骤常量。
     *
     * StepWaitCode 表示已发送验证码，等待用户提交验证码。
     */
    StepWaitCode = "wait_code",

    /**
     * StepWaitPassword 表示登录需要 2FA，等待用户提交密码。
     */
    StepWaitPassword = "wait_password",

    /**
     * StepLoggedIn 表示已完成登录。
     */
    StepLoggedIn = "logged_in",
};

/**
 * ProxyConfig 表示一份代理配置。
 * 项目为单代理配置（同时仅一份生效配置，数据库 id 固定为 1）。
 */
export class ProxyConfig {
    /**
     * 代理类型
     */
    "type": ProxyType;

    /**
     * 代理服务器地址（IP 或域名）
     */
    "address": string;

    /**
     * 代理服务器端口
     */
    "port": number;

    /**
     * 用户名（可空）
     */
    "username": string;

    /**
     * 密码（可空）
     */
    "password": string;

    /**
     * 是否启用代理
     */
    "enabled": boolean;

    /** Creates a new ProxyConfig instance. */
    constructor($$source: Partial<ProxyConfig> = {}) {
        if (!("type" in $$source)) {
            this["type"] = ProxyType.$zero;
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyConfig($$parsedSource as Partial<ProxyConfig>);
    }
}

/**
 * ProxyType 表示代理协议类型。
 */
export enum ProxyType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 支持的代理类型常量。
     *
     * SOCKS5 代理
     */
    ProxyTypeSOCKS5 = "socks5",

    /**
     * HTTP 代理（CONNECT 隧道）
     */
    ProxyTypeHTTP = "http",

    /**
     * HTTPS 代理（CONNECT 隧道）
     */
    ProxyTypeHTTPS = "https",

    /**
     * MTProto 代理（暂不支持）
     */
    ProxyTypeMTProto = "mtproto",
};

/**
 * RecentMessage 表示一条频道消息的预览数据。
 * 本结构与 download.RecentMessage 字段完全相同（json tag 一致），
 * 因 telegram 包不能反向导入 download 包（download 已导入 telegram，会形成循环导入），
 * 故在此本地定义；ApiService 层会做类型转换。
 */
export class RecentMessage {
    /**
     * MessageID 消息 ID
     */
    "message_id": number;

    /**
     * MediaType 媒体类型：video/audio/photo/document/none
     * none 表示该消息无媒体文件（纯文本消息）
     */
    "media_type": string;

    /**
     * FileName 文件名（来自 DocumentAttributeFilename，无媒体或无文件名时为空）
     */
    "file_name": string;

    /**
     * FileSize 文件大小（字节，无媒体时为 0）
     */
    "file_size": number;

    /**
     * MessageText 消息文本内容（含 caption）
     */
    "message_text": string;

    /**
     * Date 消息日期（RFC3339）
     */
    "date": string;

    /**
     * HasMedia 是否含媒体文件
     */
    "has_media": boolean;

    /** Creates a new RecentMessage instance. */
    constructor($$source: Partial<RecentMessage> = {}) {
        if (!("message_id" in $$source)) {
            this["message_id"] = 0;
        }
        if (!("media_type" in $$source)) {
            this["media_type"] = "";
        }
        if (!("file_name" in $$source)) {
            this["file_name"] = "";
        }
        if (!("file_size" in $$source)) {
            this["file_size"] = 0;
        }
        if (!("message_text" in $$source)) {
            this["message_text"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("has_media" in $$source)) {
            this["has_media"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): RecentMessage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentMessage($$parsedSource as Partial<RecentMessage>);
    }
}

/**
 * TestResult 表示代理测试或连接探测的结果。
 */
export class TestResult {
    /**
     * 是否成功
     */
    "success": boolean;

    /**
     * 结果说明或错误描述
     */
    "message": string;

    /**
     * 连接耗时（毫秒）
     */
    "latency_ms": number;

    /** Creates a new TestResult instance. */
    constructor($$source: Partial<TestResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("latency_ms" in $$source)) {
            this["latency_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TestResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestResult($$parsedSource as Partial<TestResult>);
    }
}
