// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * TaskTemplate 任务模板实体。
 */
export class TaskTemplate {
    "id": number;
    "name": string;
    "config": TaskTemplateConfig;
    "created_at": string;
    "updated_at": string;

    /** Creates a new TaskTemplate instance. */
    constructor($$source: Partial<TaskTemplate> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = (new TaskTemplateConfig());
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskTemplate instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskTemplate {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField2_0($$parsedSource["config"]);
        }
        return new TaskTemplate($$parsedSource as Partial<TaskTemplate>);
    }
}

/**
 * TaskTemplateConfig 任务模板配置，用于下载任务的复用配置。
 */
export class TaskTemplateConfig {
    /**
     * 媒体类型: video/audio/photo/document
     */
    "media_types": string[];

    /**
     * 关键词过滤
     */
    "keywords": string[];

    /**
     * 搜索词（可选，Telegram 服务器端全文搜索，与 Keywords 正交）
     */
    "search_term": string;

    /**
     * 保存目录名（必填，作为下载子目录名）
     */
    "save_dir_name": string;

    /**
     * 关键词匹配范围: filename/message/both
     */
    "keyword_match_scope": string;

    /**
     * 关键词命中模式: any(默认)/all
     */
    "keyword_match_mode": string;

    /**
     * 集数提取正则（含 capture group）
     */
    "episode_regex": string;

    /**
     * 集数正则是否必须命中
     */
    "require_episode_match": boolean;

    /**
     * 是否从最新消息开始向前扫描
     */
    "scan_from_newest": boolean;

    /**
     * 最大匹配数量（0=不限制）
     */
    "max_matches": number;

    /**
     * 遇到集数1时停止（仅 ScanFromNewest+EpisodeRegex 生效）
     */
    "stop_at_first_episode": boolean;

    /**
     * 视频文件名前缀
     */
    "video_prefix": string;

    /**
     * 并发数（≤10）
     */
    "concurrency": number;

    /**
     * 限速 bytes/s（0 表示不限）
     */
    "speed_limit": number;

    /**
     * 命名模板
     */
    "naming_template": string;

    /**
     * 扫描后是否自动下载
     */
    "auto_download": boolean;

    /** Creates a new TaskTemplateConfig instance. */
    constructor($$source: Partial<TaskTemplateConfig> = {}) {
        if (!("media_types" in $$source)) {
            this["media_types"] = [];
        }
        if (!("keywords" in $$source)) {
            this["keywords"] = [];
        }
        if (!("search_term" in $$source)) {
            this["search_term"] = "";
        }
        if (!("save_dir_name" in $$source)) {
            this["save_dir_name"] = "";
        }
        if (!("keyword_match_scope" in $$source)) {
            this["keyword_match_scope"] = "";
        }
        if (!("keyword_match_mode" in $$source)) {
            this["keyword_match_mode"] = "";
        }
        if (!("episode_regex" in $$source)) {
            this["episode_regex"] = "";
        }
        if (!("require_episode_match" in $$source)) {
            this["require_episode_match"] = false;
        }
        if (!("scan_from_newest" in $$source)) {
            this["scan_from_newest"] = false;
        }
        if (!("max_matches" in $$source)) {
            this["max_matches"] = 0;
        }
        if (!("stop_at_first_episode" in $$source)) {
            this["stop_at_first_episode"] = false;
        }
        if (!("video_prefix" in $$source)) {
            this["video_prefix"] = "";
        }
        if (!("concurrency" in $$source)) {
            this["concurrency"] = 0;
        }
        if (!("speed_limit" in $$source)) {
            this["speed_limit"] = 0;
        }
        if (!("naming_template" in $$source)) {
            this["naming_template"] = "";
        }
        if (!("auto_download" in $$source)) {
            this["auto_download"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskTemplateConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskTemplateConfig {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("media_types" in $$parsedSource) {
            $$parsedSource["media_types"] = $$createField0_0($$parsedSource["media_types"]);
        }
        if ("keywords" in $$parsedSource) {
            $$parsedSource["keywords"] = $$createField1_0($$parsedSource["keywords"]);
        }
        return new TaskTemplateConfig($$parsedSource as Partial<TaskTemplateConfig>);
    }
}

// Private type creation functions
const $$createType0 = TaskTemplateConfig.createFrom;
const $$createType1 = $Create.Array($Create.Any);
