// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ApiService 是视频提交服务 API 的 Wails 绑定服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../internal/api/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateVideoRepo 新建视频源信息。
 * 已改为本地写入：写入本地 video_repo 表及 video_tag_relation 标签关联。
 */
export function CreateVideoRepo(req: api$0.CreateVideoRepoRequest): $CancellablePromise<api$0.CreateVideoRepoResponse | null> {
    return $Call.ByID(4105021924, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteVideoRepo 批量删除视频源及其关联数据（分集/标签关联/播放历史/追番/弹幕/评论）。
 * 在事务中手动级联清理（SQLite schema 未声明 FOREIGN KEY）。
 */
export function DeleteVideoRepo(ids: number[]): $CancellablePromise<void> {
    return $Call.ByID(986861861, ids);
}

/**
 * EnsureLoggedIn 确保 API 客户端已登录（token 已设置）。
 * 已滞空：本地模式无需登录服务器，直接返回空 token。
 */
export function EnsureLoggedIn(): $CancellablePromise<$models.ToolLoginResponse> {
    return $Call.ByID(2289295134).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * FollowVideo 追番/取消追番（toggle 语义）。
 * 已改为本地写入：本地 video_follow 表 toggle，并返回最新追番状态与追番总数。
 */
export function FollowVideo(req: api$0.VideoFollowRequest): $CancellablePromise<api$0.VideoFollowResponse | null> {
    return $Call.ByID(883502047, req).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetBaseInfo 获取视频基本信息（分类、语种、标签）。
 * 已改为本地检索：从本地 video_category/video_language/video_tag 字典表读取。
 */
export function GetBaseInfo(): $CancellablePromise<api$0.BaseInfo | null> {
    return $Call.ByID(2632516502).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetBaseURL 返回当前 API 服务地址。
 * 已滞空：本地模式不再连接服务器，返回空串。
 */
export function GetBaseURL(): $CancellablePromise<string> {
    return $Call.ByID(3955474519);
}

/**
 * GetHistory 获取分集续播进度。
 * 已改为本地检索：从本地 video_user_history 表取该分集最新一条进度。
 */
export function GetHistory(episodeID: number): $CancellablePromise<api$0.HistoryProgress | null> {
    return $Call.ByID(2727396677, episodeID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetHome 获取首页聚合数据（Banner、最新上架、热门播放）。
 * 已滞空：首页已移除，返回空数据。
 */
export function GetHome(): $CancellablePromise<api$0.HomeData | null> {
    return $Call.ByID(4018154360).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetUserInfo 获取当前登录用户信息。
 * 已滞空：返回零值。本地模式无用户体系，debug 恒为 false。
 */
export function GetUserInfo(): $CancellablePromise<api$0.UserInfo | null> {
    return $Call.ByID(2658508836).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetVideoDetail 获取视频简介详情。
 * 已改为本地检索：从本地 video_repo 表读取详情，并查 video_follow 判断追番状态。
 */
export function GetVideoDetail(videoID: number): $CancellablePromise<api$0.VideoDetail | null> {
    return $Call.ByID(1849479175, videoID).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * IncrementViewCount 播放数自增。
 * 已改为本地写入：本地 video_repo.vr_view_count 自增 1。
 */
export function IncrementViewCount(vrId: number): $CancellablePromise<void> {
    return $Call.ByID(2946238642, vrId);
}

/**
 * ListDanmaku 获取分集弹幕列表。
 * 已改为本地检索：从本地 video_danmaku 表按时间升序读取。
 */
export function ListDanmaku(episodeID: number): $CancellablePromise<api$0.DanmakuItem[]> {
    return $Call.ByID(3590019874, episodeID).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * ListDiscuss 获取分集评论列表（游标分页）。
 * 已改为本地检索：从本地 video_discuss 表读取，顶级评论按 hot/latest 排序，回复按 vrd_id 升序。
 */
export function ListDiscuss(req: api$0.ListDiscussRequest): $CancellablePromise<api$0.DiscussItem[]> {
    return $Call.ByID(960392497, req).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * ListEpisodes 获取视频分集列表。
 * 已改为本地检索：从本地 video_episode 表按集数升序读取。
 */
export function ListEpisodes(videoID: number): $CancellablePromise<api$0.EpisodeItem[]> {
    return $Call.ByID(3836810163, videoID).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * ListHistory 获取最近观看列表（按 vr_id 去重，最多 10 条）。
 * 已改为本地检索：从本地 video_user_history 表按 vr_id 去重取最近一条，按 update_time 倒序。
 */
export function ListHistory(): $CancellablePromise<api$0.HistoryListItem[]> {
    return $Call.ByID(372199455).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * ListLocalDialogs 列出当前账户已订阅频道。
 * 仅返回 type=channel 的对话（过滤掉 user/private chat）。
 * keyword 为空时返回全部频道，非空时按 name 模糊搜索（内存过滤，不区分大小写）。
 * 
 * is_repo_uploaded 通过本地 video_source 表匹配：
 *   - vs_channel_id > 0 时按 channel_id 精确匹配
 *   - 否则按 vs_username 小写匹配（去掉 @ 前缀）
 * 
 * 结果按 is_repo_uploaded 降序排序（已收录优先），同名内保持原 dialogs 顺序。
 * 
 * 流程：
 *  1. 调用 manager.FetchDialogs 实时拉取当前账户的频道列表
 *  2. 仅保留 type=channel 的对话，按 keyword 内存过滤
 *  3. 查询 video_source 表构建已收录集合，匹配后置 is_repo_uploaded=true
 */
export function ListLocalDialogs(keyword: string): $CancellablePromise<$models.LocalDialog[]> {
    return $Call.ByID(1838450081, keyword).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * ListRepoSources 获取带订阅状态的视频源频道列表。
 * 已滞空：不再请求服务器，直接返回空列表。
 * 后续将改为本地 video_source 表检索 + 本地 dialogs 匹配订阅状态。
 */
export function ListRepoSources(): $CancellablePromise<$models.RepoSourceWithSubscription[]> {
    return $Call.ByID(1157563241).then(($result: any) => {
        return $$createType26($result);
    });
}

/**
 * PostDanmaku 发送弹幕。
 * 已改为本地写入：写入本地 video_danmaku 表。
 */
export function PostDanmaku(req: api$0.DanmakuPostRequest): $CancellablePromise<api$0.DanmakuItem | null> {
    return $Call.ByID(2504563828, req).then(($result: any) => {
        return $$createType27($result);
    });
}

/**
 * PostDiscuss 发表评论或回复。
 * 已改为本地写入：写入本地 video_discuss 表。
 */
export function PostDiscuss(req: api$0.DiscussPostRequest): $CancellablePromise<api$0.DiscussItem | null> {
    return $Call.ByID(3287776939, req).then(($result: any) => {
        return $$createType28($result);
    });
}

/**
 * ReportHistory 上报播放进度。
 * 已改为本地写入：按 (vr_id, ve_id) UPSERT 写入本地 video_user_history 表。
 */
export function ReportHistory(req: api$0.HistoryReportRequest): $CancellablePromise<void> {
    return $Call.ByID(754424329, req);
}

/**
 * SaveRepoChannel 保存频道到服务器。
 * 已滞空：本地不收录到服务器，直接返回成功。后续将改为本地 video_source 表写入。
 */
export function SaveRepoChannel(channelID: number, username: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2977799699, channelID, username, name);
}

/**
 * SearchChannelMessages 在指定频道内按关键字搜索消息。
 * 用于频道收录页面：用户输入关键字后，前端按分页调用本方法拉取匹配消息。
 * 
 * 参数：
 *   - peerID:   频道 ID（本地 dialogs 表的 peer_id）
 *   - keyword:  搜索关键字（必填，空则返回错误）
 *   - offsetID: 分页偏移消息 ID（0 表示从最新开始）
 *   - limit:    单页条数（≤0 或 >50 由 telegram 层强制为 50）
 */
export function SearchChannelMessages(peerID: number, keyword: string, offsetID: number, limit: number): $CancellablePromise<$models.ChannelMessageSearchResult> {
    return $Call.ByID(3983685648, peerID, keyword, offsetID, limit).then(($result: any) => {
        return $$createType29($result);
    });
}

/**
 * SearchVideos 分类检索视频。
 * 已改为本地检索：从本地 video_repo 表按分类/标签/年份/季度/关键词分页检索。
 */
export function SearchVideos(req: api$0.SearchRequest): $CancellablePromise<api$0.SearchResult | null> {
    return $Call.ByID(1308172493, req).then(($result: any) => {
        return $$createType31($result);
    });
}

/**
 * SetBaseURL 设置 API 服务地址。
 * 已滞空：本地模式不再连接服务器，空实现。
 */
export function SetBaseURL(baseURL: string): $CancellablePromise<void> {
    return $Call.ByID(2920078843, baseURL);
}

/**
 * SubscribeRepoSource 订阅视频源频道。
 * 通过 username 调用 telegram 层 SubscribeChannel，订阅成功后刷新本地 dialogs 缓存。
 * 刷新缓存失败时仅日志警告，不回滚订阅（订阅已成功）。
 * 
 * 参数：
 *   - channelID: 频道 ID（保留供后续扩展使用，当前实现仅按 username 订阅）
 *   - username:  频道用户名（@xxx 或 xxx 形式，去 @ 前缀由 telegram 层处理）
 */
export function SubscribeRepoSource(channelID: number, username: string): $CancellablePromise<void> {
    return $Call.ByID(850798450, channelID, username);
}

/**
 * TestAPIConnection 测试 API 服务连通性。
 * 已滞空：本地模式不再连接服务器，直接返回成功。
 */
export function TestAPIConnection(): $CancellablePromise<string> {
    return $Call.ByID(1397195003);
}

/**
 * ToolLogin 工具登录。
 * 已滞空：本地模式无需登录服务器，直接返回空 token。
 */
export function ToolLogin(key: string): $CancellablePromise<$models.ToolLoginResponse> {
    return $Call.ByID(641149352, key).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * UploadEpisodes 批量上传分集。
 * 已改为本地写入：按 vs_channel_id+ve_message_id 去重 UPSERT 到本地 video_episode 表，
 * 并同步更新 video_repo.vr_now_count。
 */
export function UploadEpisodes(req: api$0.UploadEpisodesRequest): $CancellablePromise<api$0.UploadEpisodesResponse | null> {
    return $Call.ByID(1461223694, req).then(($result: any) => {
        return $$createType33($result);
    });
}

// Private type creation functions
const $$createType0 = api$0.CreateVideoRepoResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ToolLoginResponse.createFrom;
const $$createType3 = api$0.VideoFollowResponse.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = api$0.BaseInfo.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = api$0.HistoryProgress.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = api$0.HomeData.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = api$0.UserInfo.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = api$0.VideoDetail.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = api$0.DanmakuItem.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = api$0.DiscussItem.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = api$0.EpisodeItem.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = api$0.HistoryListItem.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $models.LocalDialog.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = $models.RepoSourceWithSubscription.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = $Create.Nullable($$createType15);
const $$createType28 = $Create.Nullable($$createType17);
const $$createType29 = $models.ChannelMessageSearchResult.createFrom;
const $$createType30 = api$0.SearchResult.createFrom;
const $$createType31 = $Create.Nullable($$createType30);
const $$createType32 = api$0.UploadEpisodesResponse.createFrom;
const $$createType33 = $Create.Nullable($$createType32);
