// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthService 是 Wails 绑定的登录认证服务。
 * 它通过持有 *telegram.ClientManager，向前端提供完整的登录流程方法：
 * API 凭据 + 手机号 → 验证码 →（可选）2FA 密码 → 登录完成，以及登出与状态查询。
 * 
 * 登出（Logout）时会联动停止 Scheduler 的所有下载任务与 Listener 的实时监听，
 * 清除本地会话与 dialogs 缓存并停止客户端，但保留任务历史、下载记录、模板、设置、代理与订阅。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as telegram$0 from "../internal/telegram/models.js";

/**
 * GetLoginStatus 返回当前登录状态。
 * 返回值：
 *   - bool：是否已登录（authenticated）
 *   - LoginStep：当前登录流程步骤
 *   - error：仅在系统级错误时返回
 */
export function GetLoginStatus(): $CancellablePromise<[boolean, telegram$0.LoginStep]> {
    return $Call.ByID(1196992);
}

/**
 * Login 发起登录流程：设置 API 凭据，在后台启动客户端，
 * 等待客户端就绪后向指定手机号发送验证码。
 * 返回 nil 表示验证码已发送，前端应展示验证码输入框并调用 SubmitCode。
 * 
 * 若客户端已启动则复用现有连接；若已登录则直接返回 nil。
 */
export function Login(apiID: number, apiHash: string, phone: string): $CancellablePromise<void> {
    return $Call.ByID(1703500436, apiID, apiHash, phone);
}

/**
 * Logout 登出当前账号并清理本地会话。
 * 流程：
 *  1. 停止所有下载任务（将进行中的任务状态改为 paused，不删除任务记录）
 *  2. 停止实时监听服务
 *  3. 若客户端已启动且已登录，调用 Telegram API 登出
 *  4. 清除 SQLite sessions 表中的会话记录
 *  5. 停止 Telegram 客户端（Stop 内部会重置 authenticated=false、authFlow=nil）
 * 
 * 保留：tasks 表、download_records 表、task_templates 表、proxy 表、settings 表、subscriptions 表。
 * 登出后下次启动将无法恢复登录态，需重新走登录流程。
 */
export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(1103673793);
}

/**
 * ResendCode 重新发送验证码到上一次使用的手机号。
 * 验证码过期或未收到时可调用。
 */
export function ResendCode(): $CancellablePromise<void> {
    return $Call.ByID(1051576329);
}

/**
 * RestoreSession 在应用启动时尝试自动恢复已保存的会话。
 * 参数 fallbackAPIID / fallbackAPIHash 为前端传入的后备凭据（来自 localStorage），
 * 当后端 settings 表未保存凭据时使用。
 * 
 * 流程：
 *  1. 若已认证，直接返回 true
 *  2. 若客户端未启动：
 *     a. 先从后端 settings 表加载凭据；若无则用前端传入的后备凭据
 *     b. 检查 sessions 表是否存在会话记录
 *     c. 有凭据+有会话 → 启动客户端并等待就绪
 *  3. 返回当前认证状态
 * 
 * 返回 true 表示已登录，前端应跳转主界面；false 表示需要走登录流程。
 */
export function RestoreSession(fallbackAPIID: number, fallbackAPIHash: string): $CancellablePromise<boolean> {
    return $Call.ByID(3229820657, fallbackAPIID, fallbackAPIHash);
}

/**
 * SubmitCode 提交用户收到的验证码。
 * 返回当前登录步骤：
 *   - logged_in：登录成功（无需 2FA）
 *   - wait_password：需要 2FA 密码，前端应展示密码输入框
 */
export function SubmitCode(code: string): $CancellablePromise<telegram$0.LoginStep> {
    return $Call.ByID(2157295878, code);
}

/**
 * SubmitPassword 提交 2FA 密码完成登录。
 * 仅在 SubmitCode 返回 wait_password 后调用有效。
 */
export function SubmitPassword(password: string): $CancellablePromise<void> {
    return $Call.ByID(2717805710, password);
}
