// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BangumiService Bangumi 元数据检索的 Wails 绑定服务。
 * bangumi access token 不持久化，由前端在筛选弹窗填入并用 localStorage 缓存，
 * 每次调用时通过请求参数 token 透传到后端，后端临时设置到 client 后发请求。
 * 代理配置复用 telegram.ProxyConfig（同一份 proxy 表），每次请求前刷新 client transport。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../internal/api/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BrowseSubjects 按类型/年月浏览条目（GET /v0/subjects）。
 * token 为 bangumi access token，空则匿名访问（有速率限制，看不到 NSFW）。
 * userAgent 为 User-Agent（必填，格式 用户名/应用名），由前端透传。
 */
export function BrowseSubjects(req: api$0.BangumiBrowseRequest, token: string, userAgent: string): $CancellablePromise<api$0.BangumiPagedSubject | null> {
    return $Call.ByID(654597829, req, token, userAgent).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DownloadImage 代理下载 bangumi 图片。
 * 后端下载后返回字节，前端可自行处理。
 * userAgent 为 User-Agent（必填，格式 用户名/应用名），由前端透传。
 */
export function DownloadImage(imageURL: string, userAgent: string): $CancellablePromise<$models.BangumiImageResponse | null> {
    return $Call.ByID(1883354147, imageURL, userAgent).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetEpisodes 获取条目章节列表。
 * GET /v0/episodes?subject_id=&type=&limit=&offset=
 * epType：0=本篇 1=SP 2=OP 3=ED 4=PV 5=MAD 6=其他；传 -1 表示不按类型筛选。
 */
export function GetEpisodes(subjectID: number, epType: number, limit: number, offset: number, token: string, userAgent: string): $CancellablePromise<api$0.BangumiPagedEpisode | null> {
    return $Call.ByID(3502306900, subjectID, epType, limit, offset, token, userAgent).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetSubject 获取条目详情。
 * GET /v0/subjects/{subject_id}，cache 300s。
 */
export function GetSubject(subjectID: number, token: string, userAgent: string): $CancellablePromise<api$0.BangumiSubject | null> {
    return $Call.ByID(243202966, subjectID, token, userAgent).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = api$0.BangumiPagedSubject.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = api$0.BangumiImageResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = api$0.BangumiPagedEpisode.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = api$0.BangumiSubject.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
