// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DebugService 提供运行时 DOM 调试能力。
 * 通过 mux 拦截 /__debug HTTP 请求，emit 事件给前端，
 * 前端执行 DOM 查询后调用 SubmitResult 回传结果。
 * HTTP handler 同步等待结果（带超时），返回给调用方。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Inspect 发送 debug:inspect 事件给前端，同步等待结果。
 * 由 mux /__debug handler 调用。
 */
export function Inspect(params: { [_ in string]?: any }): $CancellablePromise<string> {
    return $Call.ByID(2286973330, params);
}

/**
 * SetEmitter 注入事件发射器（main.go 阶段 3 调用）。
 */
export function SetEmitter(emit: any): $CancellablePromise<void> {
    return $Call.ByID(679015444, emit);
}

/**
 * StartDebugHTTPServer 在 dev 模式下启动独立 HTTP 服务器（9255 端口），
 * 供外部 curl 调试 DOM。生产模式（无 DEV 环境变量）为空操作。
 * 
 * dev 模式下 Wails 的 mux 无法被外部请求触达（9245 是 Vite dev server），
 * 因此需要独立端口。检测 DEV=true 或 WAILS_DEV=true 环境变量决定是否启动。
 */
export function StartDebugHTTPServer(): $CancellablePromise<void> {
    return $Call.ByID(2288433358);
}

/**
 * SubmitResult 是 Wails 绑定方法，由前端调用回传 DOM 查询结果。
 */
export function SubmitResult(result: string): $CancellablePromise<void> {
    return $Call.ByID(940781431, result);
}
