// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DialogService 是 Wails 绑定的对话列表服务。
 * 它同时持有 *telegram.ClientManager 与 *sql.DB：
 *   - 通过 ClientManager 调用 Telegram API 拉取最新对话
 *   - 通过 sql.DB 读取/写入本地缓存的对话列表
 * 
 * 所有方法首字母大写，供 Wails 自动绑定暴露给前端。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as telegram$0 from "../internal/telegram/models.js";

/**
 * CheckAccess 校验当前账号是否有权限访问指定对话（频道/群组/用户）。
 * 
 * 参数：
 *   - peerID: 对端 ID
 *   - accessHash: 访问哈希（频道/用户必填，群组可传 0）
 * 
 * 返回 nil 表示有访问权限；返回错误描述具体原因。
 * 该方法供前端在用户选择某个频道后、进入频道详情前调用，提前发现无权限情况。
 */
export function CheckAccess(peerID: number, accessHash: number): $CancellablePromise<void> {
    return $Call.ByID(2765204197, peerID, accessHash);
}

/**
 * GetDialog 按 peer_id 查询单个对话。
 * 不存在时返回错误。
 */
export function GetDialog(peerID: number): $CancellablePromise<telegram$0.DialogInfo> {
    return $Call.ByID(3049001059, peerID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListDialogs 实时拉取并返回当前账户的对话列表。
 * 不读本地缓存，每次都从 Telegram API 拉取最新数据。
 * 返回错误仅在系统级故障（未登录、API 调用失败等）时出现。
 */
export function ListDialogs(): $CancellablePromise<telegram$0.DialogInfo[]> {
    return $Call.ByID(98474962).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RefreshDialogs 强制从 Telegram 拉取最新对话列表并更新 SQLite 缓存。
 * 适用于用户手动点击"刷新"按钮、或登录后重建 accessHash 缓存的场景。
 */
export function RefreshDialogs(): $CancellablePromise<telegram$0.DialogInfo[]> {
    return $Call.ByID(1369002789).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SearchDialogs 实时拉取并按 name 模糊搜索当前账户的对话（不区分大小写）。
 * keyword 为空时返回全部对话。
 * 每次都从 Telegram API 拉取最新数据，不读本地缓存。
 */
export function SearchDialogs(keyword: string): $CancellablePromise<telegram$0.DialogInfo[]> {
    return $Call.ByID(184147642, keyword).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = telegram$0.DialogInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
