// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadService 是 Wails 绑定的下载任务服务。
 * 它组合了 Scanner（扫描阶段）与 Scheduler（下载阶段），
 * 向前端提供完整的下载任务生命周期管理方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as download$0 from "../internal/download/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConfirmStart 在任务处于"待确认"状态（扫描完成但未自动下载）时，
 * 由用户确认后开始下载。
 */
export function ConfirmStart(taskID: number): $CancellablePromise<void> {
    return $Call.ByID(1041783589, taskID);
}

/**
 * CreateTask 创建下载任务并立即在后台启动扫描阶段。
 * 
 * 流程：
 *  1. 在 SQLite 中创建任务（status=scanning）
 *  2. 在后台 goroutine 中执行扫描（Scanner.Scan）
 *  3. 扫描完成后，若 AutoDownload=true 则自动启动下载（Scheduler.StartTask）
 *  4. 返回 taskID 供前端跟踪
 */
export function CreateTask(cfg: download$0.TaskConfig): $CancellablePromise<number> {
    return $Call.ByID(602765748, cfg);
}

/**
 * CreateTaskFromMessages 基于消息 ID 列表直接创建下载任务并启动下载。
 * 用于首页/分类页视频卡片上的下载入口：用户在选集弹窗选择分集后调用此方法。
 * 跳过扫描阶段，直接拉取消息元数据 → 创建下载记录 → 启动下载。
 * 
 * 返回新任务 ID。任务创建与下载启动在后台 goroutine 中执行，
 * 前端通过 task:status 事件跟踪状态变更。
 */
export function CreateTaskFromMessages(req: download$0.CreateTaskFromMessagesRequest): $CancellablePromise<number> {
    return $Call.ByID(3971852920, req);
}

/**
 * CreateTaskFromMessagesSync 是 CreateTaskFromMessages 的同步版本，
 * 阻塞直到任务创建完成（含消息拉取与下载启动），返回任务 ID。
 * 前端若需立即拿到 task_id 用于跳转或操作，调用此方法。
 */
export function CreateTaskFromMessagesSync(req: download$0.CreateTaskFromMessagesRequest): $CancellablePromise<number> {
    return $Call.ByID(239292723, req);
}

/**
 * DeleteRecord 删除指定的下载记录。
 * 用于用户手动移除匹配到的不需要的文件。
 * 注意：若记录正在下载中，本方法不主动取消下载 goroutine，仅从数据库删除；
 * 若需安全删除，建议在任务非 downloading 状态下操作。
 */
export function DeleteRecord(recordID: number): $CancellablePromise<void> {
    return $Call.ByID(580902271, recordID);
}

/**
 * DeleteTask 删除指定任务及其所有下载记录。
 */
export function DeleteTask(taskID: number): $CancellablePromise<void> {
    return $Call.ByID(18238855, taskID);
}

/**
 * FetchRecentMessages 拉取频道最新的若干条消息（默认 100 条），返回完整内容供前端展示。
 * 
 * 用于"测试匹配"弹窗的本地筛选模式：前端一次性拉取消息列表，
 * 用户复制文本作为关键词后在前端本地实时筛选，无需反复请求后端。
 * 
 * 参数：
 *   - peerID: 频道/群组/用户 ID
 *   - limit: 拉取条数（≤100，0 表示用默认值 100）
 */
export function FetchRecentMessages(peerID: number, limit: number): $CancellablePromise<download$0.RecentMessage[]> {
    return $Call.ByID(1755093804, peerID, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetEpisodeDownloadStatus 查询指定频道下多个消息 ID 的下载状态。
 * 用于选集弹窗展示每集是否已下载（"仅未下载"筛选）。
 * 返回与传入 messageIDs 等长的状态列表，顺序一致。
 */
export function GetEpisodeDownloadStatus(channelID: number, messageIDs: number[]): $CancellablePromise<download$0.EpisodeDownloadStatus[]> {
    return $Call.ByID(1083006570, channelID, messageIDs).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetTask 获取单个下载任务。
 */
export function GetTask(id: number): $CancellablePromise<download$0.Task> {
    return $Call.ByID(2093116190, id).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ListTaskRecords 列出指定任务下的所有下载记录。
 * 同时根据任务命名模板填充每条记录的 RenderedName 字段，
 * 便于前端展示渲染后的下载文件名（含集数、视频前缀等）。
 */
export function ListTaskRecords(taskID: number): $CancellablePromise<download$0.DownloadRecord[]> {
    return $Call.ByID(3508711058, taskID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ListTasks 列出所有下载任务（按 created_at 倒序）。
 */
export function ListTasks(): $CancellablePromise<download$0.Task[]> {
    return $Call.ByID(4281489785).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * OpenTaskDir 打开指定任务的下载目录（在系统文件管理器中打开）。
 * 任务目录由 SaveDirName 决定，位于下载根目录下。
 */
export function OpenTaskDir(taskID: number): $CancellablePromise<void> {
    return $Call.ByID(2044942559, taskID);
}

/**
 * PauseTask 暂停指定任务。
 */
export function PauseTask(taskID: number): $CancellablePromise<void> {
    return $Call.ByID(3001636964, taskID);
}

/**
 * PreviewMatch 测试匹配：在创建任务前预览匹配效果。
 * 按给定配置扫描频道历史消息，匹配文件后通过事件推送（scan:preview:matched / scan:preview:progress），
 * 不创建任务、不创建下载记录、不更新扫描位置。
 * 
 * 用途：在频道配置抽屉中点击"测试匹配"按钮调用，弹窗实时显示匹配进度与命中文件，
 * 便于用户调整配置（媒体类型、关键词、匹配范围）后再创建任务。
 * 
 * 返回匹配到的文件总数。
 */
export function PreviewMatch(cfg: download$0.TaskConfig): $CancellablePromise<number> {
    return $Call.ByID(1973862480, cfg);
}

/**
 * ReorderTaskRecords 接收用户在前端拖拽后的有序记录 ID 列表，写回 sort_order。
 * 用于"待排序"状态下的手动排序。
 */
export function ReorderTaskRecords(taskID: number, orderedIDs: number[]): $CancellablePromise<void> {
    return $Call.ByID(1880204757, taskID, orderedIDs);
}

/**
 * ResumeTask 恢复指定任务。
 */
export function ResumeTask(taskID: number): $CancellablePromise<void> {
    return $Call.ByID(973267175, taskID);
}

/**
 * RetryFailed 重试指定任务的所有失败记录。
 */
export function RetryFailed(taskID: number): $CancellablePromise<void> {
    return $Call.ByID(2101578296, taskID);
}

/**
 * SortTaskRecords 对指定任务的下载记录按指定键排序，并持久化 sort_order。
 * 用于"待排序"状态（StatusAwaitingSort）下的自动排序。
 * 
 * 参数：
 *   - taskID: 任务 ID
 *   - sortBy: 排序键（episode/message_id/date）
 *   - ascending: true 升序，false 降序
 * 
 * 注意：按 episode 排序时无法提取集数（episode_number=NULL）的记录始终排在最后，
 * 升降序不影响这部分记录的相对顺序（按 message_id ASC 兜底）。
 */
export function SortTaskRecords(taskID: number, sortBy: $models.SortBy, ascending: boolean): $CancellablePromise<void> {
    return $Call.ByID(4014580962, taskID, sortBy, ascending);
}

/**
 * StartDownloadAfterSort 在用户确认排序后启动下载。
 * 流程：
 *  1. 校验任务状态为 StatusAwaitingSort（非此状态拒绝）
 *  2. 更新任务状态为 StatusDownloading
 *  3. 调用 Scheduler.StartTask 开始下载
 */
export function StartDownloadAfterSort(taskID: number): $CancellablePromise<void> {
    return $Call.ByID(4225126203, taskID);
}

// Private type creation functions
const $$createType0 = download$0.RecentMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = download$0.EpisodeDownloadStatus.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = download$0.Task.createFrom;
const $$createType5 = download$0.DownloadRecord.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($$createType4);
