// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ListenerService 是 Wails 绑定的实时监听服务。
 * 它组合了 *sql.DB 与 *download.Listener，向前端提供：
 *   - 订阅的 CRUD（Subscribe / Unsubscribe / ListSubscriptions / GetSubscription）
 *   - 监听服务的启停控制（StartListener / StopListener / IsListenerRunning）
 * 
 * 所有方法首字母大写，供 Wails 自动绑定暴露给前端。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as download$0 from "../internal/download/models.js";

/**
 * GetSubscription 按 dialog_peer_id 查询单条订阅。
 */
export function GetSubscription(dialogPeerID: number): $CancellablePromise<download$0.Subscription> {
    return $Call.ByID(2852329686, dialogPeerID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * IsListenerRunning 返回监听服务是否正在运行。
 */
export function IsListenerRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(1063997644);
}

/**
 * ListSubscriptions 列出所有订阅。
 */
export function ListSubscriptions(): $CancellablePromise<download$0.Subscription[]> {
    return $Call.ByID(3889827869).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * StartListener 启动监听服务。
 * 若监听已在运行则直接返回 nil。
 * 客户端必须已登录，否则返回错误。
 */
export function StartListener(): $CancellablePromise<void> {
    return $Call.ByID(2853952011);
}

/**
 * StopListener 停止监听服务。
 * 正在进行的下载不受影响。
 */
export function StopListener(): $CancellablePromise<void> {
    return $Call.ByID(3827727861);
}

/**
 * Subscribe 创建或更新订阅。
 * 若 dialog_peer_id 已存在则更新，否则创建新订阅。
 * 返回订阅的 ID。
 */
export function Subscribe(sub: download$0.Subscription): $CancellablePromise<number> {
    return $Call.ByID(2826811239, sub);
}

/**
 * Unsubscribe 按 ID 删除订阅。
 */
export function Unsubscribe(id: number): $CancellablePromise<void> {
    return $Call.ByID(1217352554, id);
}

// Private type creation functions
const $$createType0 = download$0.Subscription.createFrom;
const $$createType1 = $Create.Array($$createType0);
