// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../internal/api/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as download$0 from "../internal/download/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as telegram$0 from "../internal/telegram/models.js";

/**
 * BangumiImageResponse 代理下载的图片响应。
 */
export const BangumiImageResponse = api$0.BangumiImageResponse;

/**
 * BangumiImageResponse 代理下载的图片响应。
 */
export type BangumiImageResponse = api$0.BangumiImageResponse;

/**
 * ChannelMessageSearchResult 频道消息搜索结果。
 */
export class ChannelMessageSearchResult {
    /**
     * 当前页消息列表
     */
    "list": telegram$0.RecentMessage[];

    /**
     * 下一页 OffsetID，0 表示无更多
     */
    "next_offset_id": number;

    /**
     * 本页返回条数
     */
    "total": number;

    /** Creates a new ChannelMessageSearchResult instance. */
    constructor($$source: Partial<ChannelMessageSearchResult> = {}) {
        if (!("list" in $$source)) {
            this["list"] = [];
        }
        if (!("next_offset_id" in $$source)) {
            this["next_offset_id"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelMessageSearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ChannelMessageSearchResult {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("list" in $$parsedSource) {
            $$parsedSource["list"] = $$createField0_0($$parsedSource["list"]);
        }
        return new ChannelMessageSearchResult($$parsedSource as Partial<ChannelMessageSearchResult>);
    }
}

/**
 * Downloader 由 party_downloader.go 的 PartyDownloader 类型实现。
 * 本接口声明在此处，使 PartyService 可在 party_downloader.go 完成前编译通过。
 * 
 * 方法语义：
 *   - GetBlocks: 返回 240 块位图（已下载标记）、当前播放块索引、正在下载块索引、下载速度（字节/秒）
 *   - SetPlayingBlock: 设置当前播放块索引（影响预载策略）
 *   - SwitchToModeB: 切换到追播放头模式（从指定块开始顺序下载）
 *   - ReadRange: 读取文件指定字节范围 [start, end]，end=-1 表示读到 EOF
 *   - Cancel: 取消所有下载任务
 *   - SetOnBlocksUpdate: 设置块下载完成回调，供 PartyService 推送 Wails Event
 */
export type Downloader = any;

/**
 * EpisodeListItem 集数列表项。
 */
export class EpisodeListItem {
    /**
     * RecordID 下载记录 ID
     */
    "recordId": number;

    /**
     * EpisodeNumber 集数（nil 表示未提取到集数）
     */
    "episodeNumber": number | null;

    /**
     * EpisodeRaw 集数原始文本
     */
    "episodeRaw": string;

    /**
     * FileName 文件名
     */
    "fileName": string;

    /**
     * IsCurrent 是否为当前播放项
     */
    "isCurrent": boolean;

    /** Creates a new EpisodeListItem instance. */
    constructor($$source: Partial<EpisodeListItem> = {}) {
        if (!("recordId" in $$source)) {
            this["recordId"] = 0;
        }
        if (!("episodeNumber" in $$source)) {
            this["episodeNumber"] = null;
        }
        if (!("episodeRaw" in $$source)) {
            this["episodeRaw"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("isCurrent" in $$source)) {
            this["isCurrent"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EpisodeListItem instance from a string or object.
     */
    static createFrom($$source: any = {}): EpisodeListItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EpisodeListItem($$parsedSource as Partial<EpisodeListItem>);
    }
}

/**
 * EventPusher Wails 事件推送接口。
 * 由 events.WailsEmitter 实现（鸭子类型），避免本文件直接依赖 events 包。
 */
export type EventPusher = any;

/**
 * LocalDialog 本地频道（带服务器收录状态）。
 * 由 ApiService.ListLocalDialogs 返回，在本地 DialogInfo 基础上叠加服务器收录标记。
 */
export class LocalDialog {
    /**
     * 频道 ID
     */
    "peer_id": number;

    /**
     * 频道名称
     */
    "name": string;

    /**
     * 频道用户名（@xxx，可空）
     */
    "username": string;

    /**
     * 对话类型（仅 channel）
     */
    "type": string;

    /**
     * 是否已收录到服务器
     */
    "is_repo_uploaded": boolean;

    /** Creates a new LocalDialog instance. */
    constructor($$source: Partial<LocalDialog> = {}) {
        if (!("peer_id" in $$source)) {
            this["peer_id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("is_repo_uploaded" in $$source)) {
            this["is_repo_uploaded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalDialog instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalDialog {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalDialog($$parsedSource as Partial<LocalDialog>);
    }
}

/**
 * MainWindowOptions 是 OpenMainWindow 的入参，仅暴露业务字段。
 */
export class MainWindowOptions {
    "Title": string;
    "Width": number;
    "Height": number;
    "Resizable": boolean;
    "ShowTitleBar": boolean;

    /** Creates a new MainWindowOptions instance. */
    constructor($$source: Partial<MainWindowOptions> = {}) {
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Width" in $$source)) {
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            this["Height"] = 0;
        }
        if (!("Resizable" in $$source)) {
            this["Resizable"] = false;
        }
        if (!("ShowTitleBar" in $$source)) {
            this["ShowTitleBar"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MainWindowOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): MainWindowOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MainWindowOptions($$parsedSource as Partial<MainWindowOptions>);
    }
}

/**
 * PartyEpisode 一起看房间内的分集信息（精简版，仅含播放所需字段）。
 */
export class PartyEpisode {
    "ve_id": number;
    "ve_collect": number;
    "ve_title": string;
    "vs_channel_id": number;
    "ve_message_id": number;

    /** Creates a new PartyEpisode instance. */
    constructor($$source: Partial<PartyEpisode> = {}) {
        if (!("ve_id" in $$source)) {
            this["ve_id"] = 0;
        }
        if (!("ve_collect" in $$source)) {
            this["ve_collect"] = 0;
        }
        if (!("ve_title" in $$source)) {
            this["ve_title"] = "";
        }
        if (!("vs_channel_id" in $$source)) {
            this["vs_channel_id"] = 0;
        }
        if (!("ve_message_id" in $$source)) {
            this["ve_message_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PartyEpisode instance from a string or object.
     */
    static createFrom($$source: any = {}): PartyEpisode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PartyEpisode($$parsedSource as Partial<PartyEpisode>);
    }
}

/**
 * PartyStartResult StartParty 方法的返回值。
 */
export class PartyStartResult {
    "roomId": string;
    "wsUrl": string;
    "streamUrl": string;
    "inviteUrl": string;
    "lanIp": string;
    "ve_id": number;
    "episodeList": PartyEpisode[];

    /** Creates a new PartyStartResult instance. */
    constructor($$source: Partial<PartyStartResult> = {}) {
        if (!("roomId" in $$source)) {
            this["roomId"] = "";
        }
        if (!("wsUrl" in $$source)) {
            this["wsUrl"] = "";
        }
        if (!("streamUrl" in $$source)) {
            this["streamUrl"] = "";
        }
        if (!("inviteUrl" in $$source)) {
            this["inviteUrl"] = "";
        }
        if (!("lanIp" in $$source)) {
            this["lanIp"] = "";
        }
        if (!("ve_id" in $$source)) {
            this["ve_id"] = 0;
        }
        if (!("episodeList" in $$source)) {
            this["episodeList"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PartyStartResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PartyStartResult {
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("episodeList" in $$parsedSource) {
            $$parsedSource["episodeList"] = $$createField6_0($$parsedSource["episodeList"]);
        }
        return new PartyStartResult($$parsedSource as Partial<PartyStartResult>);
    }
}

/**
 * PartyState GetPartyState 方法的返回值，供 PartyConsole 初始化。
 */
export class PartyState {
    "roomId": string;
    "vr_id": number;
    "current_ve_id": number;
    "lanIp": string;
    "wsUrl": string;
    "streamUrl": string;
    "inviteUrl": string;
    "episodeList": PartyEpisode[];

    /**
     * Clients 当前在线客户端列表(供 PartyConsole 初始化展示)
     */
    "clients": WSClientInfo[];

    /**
     * HostName 当前房主名称
     */
    "hostName": string;

    /** Creates a new PartyState instance. */
    constructor($$source: Partial<PartyState> = {}) {
        if (!("roomId" in $$source)) {
            this["roomId"] = "";
        }
        if (!("vr_id" in $$source)) {
            this["vr_id"] = 0;
        }
        if (!("current_ve_id" in $$source)) {
            this["current_ve_id"] = 0;
        }
        if (!("lanIp" in $$source)) {
            this["lanIp"] = "";
        }
        if (!("wsUrl" in $$source)) {
            this["wsUrl"] = "";
        }
        if (!("streamUrl" in $$source)) {
            this["streamUrl"] = "";
        }
        if (!("inviteUrl" in $$source)) {
            this["inviteUrl"] = "";
        }
        if (!("episodeList" in $$source)) {
            this["episodeList"] = [];
        }
        if (!("clients" in $$source)) {
            this["clients"] = [];
        }
        if (!("hostName" in $$source)) {
            this["hostName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PartyState instance from a string or object.
     */
    static createFrom($$source: any = {}): PartyState {
        const $$createField7_0 = $$createType3;
        const $$createField8_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("episodeList" in $$parsedSource) {
            $$parsedSource["episodeList"] = $$createField7_0($$parsedSource["episodeList"]);
        }
        if ("clients" in $$parsedSource) {
            $$parsedSource["clients"] = $$createField8_0($$parsedSource["clients"]);
        }
        return new PartyState($$parsedSource as Partial<PartyState>);
    }
}

/**
 * RepoSourceWithSubscription 带订阅状态的视频源频道。
 * 由 ApiService.ListRepoSources 返回，在服务器源基础上叠加本地频道匹配结果。
 */
export class RepoSourceWithSubscription {
    /**
     * 服务器设置的频道名称
     */
    "vs_name": string;

    /**
     * 频道 ID
     */
    "vs_channel_id": number;

    /**
     * 频道用户名（@xxx，可空）
     */
    "vs_username": string;

    /**
     * 用户是否已订阅
     */
    "is_subscribed": boolean;

    /**
     * 用户本地频道名称
     */
    "dialog_name": string;

    /** Creates a new RepoSourceWithSubscription instance. */
    constructor($$source: Partial<RepoSourceWithSubscription> = {}) {
        if (!("vs_name" in $$source)) {
            this["vs_name"] = "";
        }
        if (!("vs_channel_id" in $$source)) {
            this["vs_channel_id"] = 0;
        }
        if (!("vs_username" in $$source)) {
            this["vs_username"] = "";
        }
        if (!("is_subscribed" in $$source)) {
            this["is_subscribed"] = false;
        }
        if (!("dialog_name" in $$source)) {
            this["dialog_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoSourceWithSubscription instance from a string or object.
     */
    static createFrom($$source: any = {}): RepoSourceWithSubscription {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RepoSourceWithSubscription($$parsedSource as Partial<RepoSourceWithSubscription>);
    }
}

/**
 * SortBy 定义排序键（与 download.SortBy 一致，重导出便于 Wails 绑定）。
 */
export type SortBy = download$0.SortBy;

/**
 * SourceListSyncResult 同步结果汇总，供前端展示。
 */
export class SourceListSyncResult {
    /**
     * 清单总条数
     */
    "total": number;

    /**
     * 写入/更新条数
     */
    "upserted": number;

    /**
     * 本次新订阅条数
     */
    "subscribed": number;

    /**
     * 订阅失败条数
     */
    "failed": number;

    /** Creates a new SourceListSyncResult instance. */
    constructor($$source: Partial<SourceListSyncResult> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("upserted" in $$source)) {
            this["upserted"] = 0;
        }
        if (!("subscribed" in $$source)) {
            this["subscribed"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceListSyncResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SourceListSyncResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceListSyncResult($$parsedSource as Partial<SourceListSyncResult>);
    }
}

/**
 * ToolLoginResponse 工具登录响应。
 */
export class ToolLoginResponse {
    /**
     * 访问令牌
     */
    "token": string;

    /** Creates a new ToolLoginResponse instance. */
    constructor($$source: Partial<ToolLoginResponse> = {}) {
        if (!("token" in $$source)) {
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolLoginResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolLoginResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolLoginResponse($$parsedSource as Partial<ToolLoginResponse>);
    }
}

/**
 * VideoPlayInfo 视频播放元数据。
 * 前端调用 VideoService.GetVideoPlayInfo 后可直接据此渲染播放页。
 */
export class VideoPlayInfo {
    /**
     * RecordID 当前播放的下载记录 ID
     */
    "recordId": number;

    /**
     * TaskID 所属任务 ID
     */
    "taskId": number;

    /**
     * Title 视频标题（取自任务 TaskConfig.SaveDirName）
     */
    "title": string;

    /**
     * EpisodeNumber 集数（nil 表示未提取到集数）
     */
    "episodeNumber": number | null;

    /**
     * EpisodeRaw 集数 capture group 原始文本
     */
    "episodeRaw": string;

    /**
     * FileName 文件名
     */
    "fileName": string;

    /**
     * StreamURL 流接口 URL（/api/video/stream?record_id=xxx）
     */
    "streamUrl": string;

    /**
     * PrevRecordID 上一集记录 ID（nil 表示已是第一集）
     */
    "prevRecordId": number | null;

    /**
     * NextRecordID 下一集记录 ID（nil 表示已是最后一集）
     */
    "nextRecordId": number | null;

    /**
     * EpisodeList 同任务下所有可播放视频记录（按 sort_order ASC）
     */
    "episodeList": EpisodeListItem[];

    /** Creates a new VideoPlayInfo instance. */
    constructor($$source: Partial<VideoPlayInfo> = {}) {
        if (!("recordId" in $$source)) {
            this["recordId"] = 0;
        }
        if (!("taskId" in $$source)) {
            this["taskId"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("episodeNumber" in $$source)) {
            this["episodeNumber"] = null;
        }
        if (!("episodeRaw" in $$source)) {
            this["episodeRaw"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("streamUrl" in $$source)) {
            this["streamUrl"] = "";
        }
        if (!("prevRecordId" in $$source)) {
            this["prevRecordId"] = null;
        }
        if (!("nextRecordId" in $$source)) {
            this["nextRecordId"] = null;
        }
        if (!("episodeList" in $$source)) {
            this["episodeList"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoPlayInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoPlayInfo {
        const $$createField9_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("episodeList" in $$parsedSource) {
            $$parsedSource["episodeList"] = $$createField9_0($$parsedSource["episodeList"]);
        }
        return new VideoPlayInfo($$parsedSource as Partial<VideoPlayInfo>);
    }
}

/**
 * WSClientInfo 客户端信息（welcome/client_joined 等消息中携带）。
 */
export class WSClientInfo {
    "name": string;
    "isHost": boolean;

    /** Creates a new WSClientInfo instance. */
    constructor($$source: Partial<WSClientInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isHost" in $$source)) {
            this["isHost"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WSClientInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WSClientInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WSClientInfo($$parsedSource as Partial<WSClientInfo>);
    }
}

/**
 * WindowOptions 是前端调用 OpenWindow 时提交的窗口配置。
 * 仅暴露业务关心的少量字段，其余选项由后端默认值填充。
 */
export class WindowOptions {
    /**
     * 窗口标题
     */
    "Title": string;

    /**
     * 初始宽度（px）
     */
    "Width": number;

    /**
     * 初始高度（px）
     */
    "Height": number;

    /**
     * 路由路径（如 "/download"），同时作为单例窗口的 key
     */
    "URL": string;

    /**
     * 是否允许拖拽调整大小（false 时禁用最大化按钮）
     */
    "Resizable": boolean;

    /**
     * 是否唯一窗口：true 时同 URL 已存在则聚焦而非新建
     */
    "Unique": boolean;

    /**
     * 是否显示前端自定义顶栏
     */
    "ShowTitleBar": boolean;

    /**
     * 是否主窗口：关闭时退出整个应用
     */
    "IsMain": boolean;

    /** Creates a new WindowOptions instance. */
    constructor($$source: Partial<WindowOptions> = {}) {
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Width" in $$source)) {
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            this["Height"] = 0;
        }
        if (!("URL" in $$source)) {
            this["URL"] = "";
        }
        if (!("Resizable" in $$source)) {
            this["Resizable"] = false;
        }
        if (!("Unique" in $$source)) {
            this["Unique"] = false;
        }
        if (!("ShowTitleBar" in $$source)) {
            this["ShowTitleBar"] = false;
        }
        if (!("IsMain" in $$source)) {
            this["IsMain"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowOptions($$parsedSource as Partial<WindowOptions>);
    }
}

/**
 * WindowResult 是 OpenWindow 的返回值。
 */
export class WindowResult {
    /**
     * true 表示单例窗口已存在，本次仅聚焦未新建
     */
    "AlreadyOpen": boolean;

    /** Creates a new WindowResult instance. */
    constructor($$source: Partial<WindowResult> = {}) {
        if (!("AlreadyOpen" in $$source)) {
            this["AlreadyOpen"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowResult instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowResult($$parsedSource as Partial<WindowResult>);
    }
}

// Private type creation functions
const $$createType0 = telegram$0.RecentMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = PartyEpisode.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = WSClientInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = EpisodeListItem.createFrom;
const $$createType7 = $Create.Array($$createType6);
