// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PartyService 一起看的 Wails 绑定服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetEpisodeList 查询视频的分集列表，转为 PartyEpisode 格式。
 */
export function GetEpisodeList(vrID: number): $CancellablePromise<$models.PartyEpisode[]> {
    return $Call.ByID(602105316, vrID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetPartyState 获取一起看房间状态，供 PartyConsole 初始化。
 */
export function GetPartyState(roomID: string): $CancellablePromise<$models.PartyState | null> {
    return $Call.ByID(3088123654, roomID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SetApp 注入 Wails 应用实例（main.go 阶段 3 调用）。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(203217922, app);
}

/**
 * SetDownloader 由 party_downloader.go 完成后注入 downloader 实例。
 * 供外部 sub-agent 在创建 PartyDownloader 后调用。
 * 注入时会自动设置 blocks 更新回调，用于推送 party:download_blocks Wails Event。
 */
export function SetDownloader(roomID: string, dl: $models.Downloader): $CancellablePromise<void> {
    return $Call.ByID(4251550512, roomID, dl);
}

/**
 * SetEmitter 注入事件推送器（main.go 阶段 3 调用）。
 */
export function SetEmitter(emitter: $models.EventPusher): $CancellablePromise<void> {
    return $Call.ByID(2410517559, emitter);
}

/**
 * StartParty 开启一起看。
 * 流程：
 *  1. 生成 8 位 roomId（大写字母+数字）+ 32 位 hostToken
 *  2. 查询分集列表，取第 1 集元数据
 *  3. 创建缓存目录 <configDir>/TGDownload/party_cache/<roomId>/
 *  4. 启动 PartyStreamServer（0.0.0.0:0）
 *  5. 启动 PartyWSServer（0.0.0.0:0）
 *  6. 返回 PartyStartResult（含 wsUrl/streamUrl/inviteUrl/lanIp）
 * 
 * 注：downloader 由其他 sub-agent 实现的 party_downloader.go 提供，
 * 此处仅在 rooms 表中预留 Downloader 字段为 nil，由外部 setter 注入。
 * 文件大小由 downloader 内部 fetch，本方法不预先查询。
 */
export function StartParty(vrID: number): $CancellablePromise<$models.PartyStartResult | null> {
    return $Call.ByID(2224886389, vrID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * StopParty 结束一起看。
 * 流程：
 *  1. WS 广播 host_leaving
 *  2. 关闭 WS server、Stream server
 *  3. 取消 downloader
 *  4. 删除整个缓存目录 os.RemoveAll(cacheDir)
 */
export function StopParty(roomID: string): $CancellablePromise<void> {
    return $Call.ByID(2433841811, roomID);
}

/**
 * SwitchEpisode 切换一起看房间的当前分集。
 * 由 WS handler 在收到房主 episode_change 消息时调用。
 * 返回新的 streamUrl 供 WS 广播给所有观看端。
 * 
 * 副作用:
 *   - 取消旧 Downloader(停止旧集下载)
 *   - 如果新集正好是预载的下一集 → 升级预载 DL 为当前 DL,启动新的下一集预载
 *   - 否则取消预载 DL + 删预载文件 + 创建全新 DL
 *   - 删除旧集缓存文件(仅删除旧 veID 对应的 .mp4,不删预载文件)
 *   - 重置 lastDuration(等待新集 report_duration 上报)
 */
export function SwitchEpisode(roomID: string, veID: number): $CancellablePromise<string> {
    return $Call.ByID(2484311914, roomID, veID);
}

// Private type creation functions
const $$createType0 = $models.PartyEpisode.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.PartyState.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.PartyStartResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
