// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProxyService 是 Wails 绑定的代理配置服务。
 * 它通过持有 *telegram.ClientManager 与 *sql.DB，向前端提供
 * 代理配置的读取、保存（含客户端重连）与连接测试方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as telegram$0 from "../internal/telegram/models.js";

/**
 * GetProxy 读取当前代理配置。
 * 优先从数据库读取持久化配置；若数据库无记录则返回空配置。
 * 该方法供 Wails 自动绑定暴露给前端。
 */
export function GetProxy(): $CancellablePromise<telegram$0.ProxyConfig> {
    return $Call.ByID(3599063965).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveProxy 保存代理配置并触发客户端重连（若客户端已启动）。
 * 保存成功后，若客户端正在运行，将使用新代理重建网络层；会话不会丢失。
 */
export function SaveProxy(cfg: telegram$0.ProxyConfig): $CancellablePromise<void> {
    return $Call.ByID(4020651764, cfg);
}

/**
 * TestProxy 测试给定代理配置能否成功连接到 Telegram DC。
 * 返回测试结果（成功状态、消息、延迟）。测试本身不会抛出错误，
 * 连接失败时通过 TestResult.Success=false 与 Message 描述原因；
 * 仅在系统级错误（如构造 dialer 失败）时返回 error。
 */
export function TestProxy(cfg: telegram$0.ProxyConfig): $CancellablePromise<telegram$0.TestResult> {
    return $Call.ByID(3151480927, cfg).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = telegram$0.ProxyConfig.createFrom;
const $$createType1 = telegram$0.TestResult.createFrom;
