// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 是 Wails 绑定的设置服务。
 * 它通过持有 *sql.DB 与 settings 表交互，向前端提供设置读写方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../internal/settings/models.js";

/**
 * GetDownloadDir 仅返回下载目录。
 * 前端首次启动引导时使用，避免加载全部设置。
 */
export function GetDownloadDir(): $CancellablePromise<string> {
    return $Call.ByID(927059247);
}

/**
 * GetSettings 返回当前应用设置，缺失项以默认值填充。
 * 该方法供 Wails 自动绑定暴露给前端。
 */
export function GetSettings(): $CancellablePromise<settings$0.AppSettings> {
    return $Call.ByID(3739132117).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveSettings 保存应用设置到数据库（UPSERT）。
 */
export function SaveSettings(cfg: settings$0.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(4241747588, cfg);
}

/**
 * SetDownloadDir 仅设置下载目录。
 */
export function SetDownloadDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(4050320691, dir);
}

// Private type creation functions
const $$createType0 = settings$0.AppSettings.createFrom;
