// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SourceListService 是 Wails 绑定的视频源清单同步服务。
 * 依赖 settings 读取清单 URL，依赖 telegram manager 执行订阅。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * SyncSourceList 执行一次完整的清单同步流程：
 *  1. 从 settings 读取 source_list_url（走 LoadSettings，缺失时用默认值），为空直接返回零值结果
 *  2. HTTP GET 拉取 JSON 清单
 *  3. 逐条 UPSERT 到 video_source 表（按 vs_channel_id 去重，0 时按 vs_username）
 *  4. 若 manager 已登录，拉取本地 dialogs，对清单中未订阅的 username 逐个订阅
 *  5. 订阅完成后刷新 dialogs 缓存
 * 
 * 拉取失败直接返回 error；单条订阅失败仅累加 Failed 计数，不中断流程。
 */
export function SyncSourceList(): $CancellablePromise<$models.SourceListSyncResult | null> {
    return $Call.ByID(670258230).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SourceListSyncResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
