// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TemplateService 任务模板服务，对外暴露任务模板的增删改查方法供 Wails 绑定。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as template$0 from "../internal/template/models.js";

/**
 * CreateTemplate 创建任务模板，返回新模板 ID。
 */
export function CreateTemplate(name: string, config: template$0.TaskTemplateConfig): $CancellablePromise<number> {
    return $Call.ByID(2193806665, name, config);
}

/**
 * DeleteTemplate 删除任务模板。
 */
export function DeleteTemplate(id: number): $CancellablePromise<void> {
    return $Call.ByID(1254159810, id);
}

/**
 * GetTemplate 获取单个任务模板。
 */
export function GetTemplate(id: number): $CancellablePromise<template$0.TaskTemplate> {
    return $Call.ByID(1191860683, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListTemplates 列出所有任务模板（按更新时间倒序）。
 */
export function ListTemplates(): $CancellablePromise<template$0.TaskTemplate[]> {
    return $Call.ByID(3494265718).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateTemplate 更新任务模板。
 */
export function UpdateTemplate(id: number, name: string, config: template$0.TaskTemplateConfig): $CancellablePromise<void> {
    return $Call.ByID(705854220, id, name, config);
}

// Private type creation functions
const $$createType0 = template$0.TaskTemplate.createFrom;
const $$createType1 = $Create.Array($$createType0);
