// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VideoService 视频播放服务。
 * 通过持有 *sql.DB 与 download_records 表交互，向前端提供播放元数据查询方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetEpisodeStream 根据分集的 TG 频道与消息 ID 返回可播放的流地址。
 * 返回独立流服务的绝对地址（http://127.0.0.1:<port>/api/video/episode/stream?...），
 * 由独立 HTTP server 处理，原生支持流式响应与 Range 请求，
 * 绕过 Wails3 AssetServer 对响应体的全量缓冲。
 */
export function GetEpisodeStream(channelID: number, messageID: number): $CancellablePromise<string> {
    return $Call.ByID(1714739323, channelID, messageID);
}

/**
 * GetVideoPlayInfo 获取视频播放所需的完整元数据。
 * 前端调用此方法后可直接渲染播放页（VideoPlayer + 标题 + 上下集 + 集数列表）。
 * 
 * 流程：
 *  1. 查询当前记录并校验 status=completed 且 media_type=video
 *  2. 加载任务，用 TaskConfig.SaveDirName 作为标题
 *  3. 查询同任务下所有可播放记录（集数列表）
 *  4. 定位当前记录在集数列表中的位置，计算 prev/next
 *  5. 拼接 streamUrl 并构建 EpisodeList（标记 isCurrent）
 */
export function GetVideoPlayInfo(recordID: number): $CancellablePromise<$models.VideoPlayInfo | null> {
    return $Call.ByID(826742399, recordID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetStreamBaseURL 设置独立流服务的基础地址。
 * 由 main.go 在启动独立 HTTP server 后注入，形如 http://127.0.0.1:12345。
 * GetEpisodeStream 会据此返回绝对地址，绕过 Wails3 AssetServer 的响应缓冲机制。
 */
export function SetStreamBaseURL(baseURL: string): $CancellablePromise<void> {
    return $Call.ByID(3848242608, baseURL);
}

// Private type creation functions
const $$createType0 = $models.VideoPlayInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
