// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService 是 Wails 绑定的窗口管理服务。
 * 通过 SetApp 在 main.go 阶段 3 注入 *application.App（与 events.Emitter 同模式）。
 * 
 * 单例窗口（Unique=true）以 URL 为 key 存入 unique map，
 * 窗口关闭时通过 WindowClosing 事件自动从 map 中移除。
 * 多实例窗口（Unique=false）不入注册表，由前端自行管理。
 * 
 * 主窗口（IsMain=true）关闭时调用 app.Quit() 退出整个应用。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../database/sql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseWindow 关闭指定 URL 的单例窗口。
 * 仅对 Unique=true 创建的窗口有效；多实例窗口需在前端自行关闭。
 */
export function CloseWindow(url: string): $CancellablePromise<void> {
    return $Call.ByID(3585161263, url);
}

/**
 * OpenLoginWindow 退出登录时使用：打开登录窗并关闭主窗，但不退出整个应用。
 * 主窗（URL="/"）关闭时默认会触发 app.Quit()，这里通过 closingMainWindow 标记跳过。
 * 用于 Settings 页退出登录流程：前端清完会话后调用本方法切回登录窗。
 * 
 * 注意：w.Close() 触发的 WindowClosing 事件是异步的，不能在 Close() 之后立刻
 * 重置 closingMainWindow，否则事件回调执行时标记已被重置回 false，仍会 Quit。
 * 这里保持 closingMainWindow=true，由主窗的 WindowClosing 事件回调自身重置。
 */
export function OpenLoginWindow(): $CancellablePromise<$models.WindowResult> {
    return $Call.ByID(500733670).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * OpenMainWindow 在登录流程完成后打开主窗口。
 * 主窗统一以 "/" 打开，TG 登录已在登录窗内完成（扫码->检测->电报表单），
 * 能调到此方法说明用户已通过完整登录流程。
 */
export function OpenMainWindow(opts: $models.MainWindowOptions): $CancellablePromise<$models.WindowResult> {
    return $Call.ByID(931600700, opts).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * OpenPartyConsoleWindow 打开"一起看"控制台窗口。
 * 窗口尺寸 800×600,带前端自定义顶栏(showTitleBar=true)且可调整大小(resizable=true)。
 * URL 形如 /party-console/<roomId>,前端路由表已注册对应路由。
 * 单例窗口:同 roomId 已存在则聚焦而非新建。
 */
export function OpenPartyConsoleWindow(roomId: string): $CancellablePromise<$models.WindowResult> {
    return $Call.ByID(1442107384, roomId).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * OpenStartupWindow 是应用启动时的窗口选择逻辑。
 * 统一开登录窗，由前端 Login.vue 检测微信+TG 登录态决定后续流程：
 *   - 有微信 token + TG 已登录 -> 前端调 openMainWindow 开主窗
 *   - 有微信 token + TG 未登录 -> 前端展示电报登录表单
 *   - 无微信 token -> 前端显示二维码
 * 
 * 不在 Go 侧判断 TG 会话，因为会话记录存在不代表会话有效（登录失败也会留记录），
 * 真正的有效性检测在前端 getLoginStatus 异步完成，避免 Go 侧阻塞。
 */
export function OpenStartupWindow(): $CancellablePromise<$models.WindowResult> {
    return $Call.ByID(4060160494).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * OpenWindow 创建或聚焦一个窗口。
 * 
 * 行为：
 *   - Unique=true 且同 URL 窗口已存在：调用 Show + Focus，返回 AlreadyOpen=true
 *   - Unique=true 且不存在：新建并存入 unique map，注册关闭事件自动清理
 *   - Unique=false：直接新建，不入 map
 * 
 * URL 会被拼接为 hash 路由格式 "#<URL>?titlebar=<bool>&resizable=<bool>"，
 * 前端路由守卫解析 query 写入 route.meta，供顶栏组件读取。
 */
export function OpenWindow(opts: $models.WindowOptions): $CancellablePromise<$models.WindowResult> {
    return $Call.ByID(4137044405, opts).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetApp 注入 Wails 应用实例。
 * 必须在 app 创建后、运行前调用（main.go 阶段 3）。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3393886178, app);
}

/**
 * SetAuthService 注入 AuthService 引用，供 OpenMainWindow 恢复 TG 会话。
 * 参数用 any 避免 Wails binding 把接口类型当 model 生成（引发 TS 重复定义）。
 */
export function SetAuthService(auth: any): $CancellablePromise<void> {
    return $Call.ByID(1895803296, auth);
}

/**
 * SetDB 注入数据库引用，供 OpenStartupWindow 判断登录状态。
 */
export function SetDB(db: sql$0.DB | null): $CancellablePromise<void> {
    return $Call.ByID(3811813025, db);
}

/**
 * SetWindowTitle 同步更新窗口的系统任务栏标题。
 * 前端路由切换时调用此方法，保持任务栏标题与顶栏标题一致。
 */
export function SetWindowTitle(url: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(2261627871, url, title);
}

// Private type creation functions
const $$createType0 = $models.WindowResult.createFrom;
