// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings 表示应用的全部全局设置项。
 * 各字段通过 JSON 标签与前端交互。
 */
export class AppSettings {
    /**
     * 主题："dark" 或 "light"
     */
    "theme": string;

    /**
     * 默认并发数（≤10）
     */
    "concurrency": number;

    /**
     * 默认限速 bytes/s（0 表示不限）
     */
    "speed_limit": number;

    /**
     * 默认命名模板
     */
    "naming_template": string;

    /**
     * 下载目录
     */
    "download_dir": string;

    /**
     * 界面语言（固定 "zh-CN"）
     */
    "language": string;

    /**
     * 默认自动下载开关
     */
    "auto_download": boolean;

    /**
     * 视频源频道清单 URL（GitHub Raw），空表示不启用
     */
    "source_list_url": string;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("concurrency" in $$source)) {
            this["concurrency"] = 0;
        }
        if (!("speed_limit" in $$source)) {
            this["speed_limit"] = 0;
        }
        if (!("naming_template" in $$source)) {
            this["naming_template"] = "";
        }
        if (!("download_dir" in $$source)) {
            this["download_dir"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("auto_download" in $$source)) {
            this["auto_download"] = false;
        }
        if (!("source_list_url" in $$source)) {
            this["source_list_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}
