// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BangumiBrowseRequest 浏览条目查询参数。
 * 对照 GET /v0/subjects：type 必填，其余可选。
 */
export class BangumiBrowseRequest {
    /**
     * 必填，条目类型
     */
    "Type": BangumiSubjectType;

    /**
     * 可选，条目分类（动画下 TV/OVA/Movie/WEB）
     */
    "Cat": string;

    /**
     * 可选，仅书籍有效
     */
    "Series": boolean;

    /**
     * 可选，仅游戏有效
     */
    "Plat": string;

    /**
     * 可选，date / rank
     */
    "Sort": string;

    /**
     * 可选，年份
     */
    "Year": number;

    /**
     * 可选，月份 1~12
     */
    "Month": number;

    /**
     * 可选，≤50，默认 30
     */
    "Limit": number;

    /**
     * 可选，默认 0
     */
    "Offset": number;

    /** Creates a new BangumiBrowseRequest instance. */
    constructor($$source: Partial<BangumiBrowseRequest> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = BangumiSubjectType.$zero;
        }
        if (!("Cat" in $$source)) {
            this["Cat"] = "";
        }
        if (!("Series" in $$source)) {
            this["Series"] = false;
        }
        if (!("Plat" in $$source)) {
            this["Plat"] = "";
        }
        if (!("Sort" in $$source)) {
            this["Sort"] = "";
        }
        if (!("Year" in $$source)) {
            this["Year"] = 0;
        }
        if (!("Month" in $$source)) {
            this["Month"] = 0;
        }
        if (!("Limit" in $$source)) {
            this["Limit"] = 0;
        }
        if (!("Offset" in $$source)) {
            this["Offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BangumiBrowseRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BangumiBrowseRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BangumiBrowseRequest($$parsedSource as Partial<BangumiBrowseRequest>);
    }
}

/**
 * BangumiCollection 收藏人数聚合。
 */
export class BangumiCollection {
    "wish": number;
    "collect": number;
    "doing": number;
    "on_hold": number;
    "dropped": number;

    /** Creates a new BangumiCollection instance. */
    constructor($$source: Partial<BangumiCollection> = {}) {
        if (!("wish" in $$source)) {
            this["wish"] = 0;
        }
        if (!("collect" in $$source)) {
            this["collect"] = 0;
        }
        if (!("doing" in $$source)) {
            this["doing"] = 0;
        }
        if (!("on_hold" in $$source)) {
            this["on_hold"] = 0;
        }
        if (!("dropped" in $$source)) {
            this["dropped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BangumiCollection instance from a string or object.
     */
    static createFrom($$source: any = {}): BangumiCollection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BangumiCollection($$parsedSource as Partial<BangumiCollection>);
    }
}

/**
 * BangumiEpisode 章节。
 */
export class BangumiEpisode {
    "id": number;
    "type": number;
    "name": string;
    "name_cn": string;
    "sort": number;
    "ep": number;
    "airdate": string;
    "comment": number;
    "duration": string;
    "desc": string;
    "disc": number;
    "duration_seconds": number;

    /** Creates a new BangumiEpisode instance. */
    constructor($$source: Partial<BangumiEpisode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("type" in $$source)) {
            this["type"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("name_cn" in $$source)) {
            this["name_cn"] = "";
        }
        if (!("sort" in $$source)) {
            this["sort"] = 0;
        }
        if (!("ep" in $$source)) {
            this["ep"] = 0;
        }
        if (!("airdate" in $$source)) {
            this["airdate"] = "";
        }
        if (!("comment" in $$source)) {
            this["comment"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = "";
        }
        if (!("desc" in $$source)) {
            this["desc"] = "";
        }
        if (!("disc" in $$source)) {
            this["disc"] = 0;
        }
        if (!("duration_seconds" in $$source)) {
            this["duration_seconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BangumiEpisode instance from a string or object.
     */
    static createFrom($$source: any = {}): BangumiEpisode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BangumiEpisode($$parsedSource as Partial<BangumiEpisode>);
    }
}

/**
 * BangumiImageResponse 下载图片响应。
 * 由后端代理下载 bangumi 图片，返回字节给前端，避免前端 CORS 问题。
 */
export class BangumiImageResponse {
    /**
     * 文件名（含扩展名）
     */
    "file_name": string;

    /**
     * 图片内容字节数组
     */
    "bytes": string;

    /**
     * 字节数
     */
    "size": number;

    /**
     * MIME 类型
     */
    "mime_type": string;

    /** Creates a new BangumiImageResponse instance. */
    constructor($$source: Partial<BangumiImageResponse> = {}) {
        if (!("file_name" in $$source)) {
            this["file_name"] = "";
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("mime_type" in $$source)) {
            this["mime_type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BangumiImageResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): BangumiImageResponse {
        const $$createField1_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bytes" in $$parsedSource) {
            $$parsedSource["bytes"] = $$createField1_0($$parsedSource["bytes"]);
        }
        return new BangumiImageResponse($$parsedSource as Partial<BangumiImageResponse>);
    }
}

/**
 * BangumiImages 条目封面图，包含多种尺寸 URL。
 */
export class BangumiImages {
    "large": string;
    "common": string;
    "medium": string;
    "small": string;
    "grid": string;

    /** Creates a new BangumiImages instance. */
    constructor($$source: Partial<BangumiImages> = {}) {
        if (!("large" in $$source)) {
            this["large"] = "";
        }
        if (!("common" in $$source)) {
            this["common"] = "";
        }
        if (!("medium" in $$source)) {
            this["medium"] = "";
        }
        if (!("small" in $$source)) {
            this["small"] = "";
        }
        if (!("grid" in $$source)) {
            this["grid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BangumiImages instance from a string or object.
     */
    static createFrom($$source: any = {}): BangumiImages {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BangumiImages($$parsedSource as Partial<BangumiImages>);
    }
}

/**
 * BangumiPagedEpisode 分页章节列表。
 */
export class BangumiPagedEpisode {
    "total": number;
    "limit": number;
    "offset": number;
    "data": BangumiEpisode[];

    /** Creates a new BangumiPagedEpisode instance. */
    constructor($$source: Partial<BangumiPagedEpisode> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("data" in $$source)) {
            this["data"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BangumiPagedEpisode instance from a string or object.
     */
    static createFrom($$source: any = {}): BangumiPagedEpisode {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField3_0($$parsedSource["data"]);
        }
        return new BangumiPagedEpisode($$parsedSource as Partial<BangumiPagedEpisode>);
    }
}

/**
 * BangumiPagedSubject 分页条目列表（GET /v0/subjects、POST /v0/search/subjects 共用）。
 */
export class BangumiPagedSubject {
    "total": number;
    "limit": number;
    "offset": number;
    "data": BangumiSubject[];

    /** Creates a new BangumiPagedSubject instance. */
    constructor($$source: Partial<BangumiPagedSubject> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("data" in $$source)) {
            this["data"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BangumiPagedSubject instance from a string or object.
     */
    static createFrom($$source: any = {}): BangumiPagedSubject {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField3_0($$parsedSource["data"]);
        }
        return new BangumiPagedSubject($$parsedSource as Partial<BangumiPagedSubject>);
    }
}

/**
 * BangumiRating 评分聚合。
 */
export class BangumiRating {
    "rank": number;
    "total": number;
    "score": number;

    /**
     * "1"~"10" 各分数段人数
     */
    "count": { [_ in string]?: number };

    /** Creates a new BangumiRating instance. */
    constructor($$source: Partial<BangumiRating> = {}) {
        if (!("rank" in $$source)) {
            this["rank"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }
        if (!("count" in $$source)) {
            this["count"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BangumiRating instance from a string or object.
     */
    static createFrom($$source: any = {}): BangumiRating {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("count" in $$parsedSource) {
            $$parsedSource["count"] = $$createField3_0($$parsedSource["count"]);
        }
        return new BangumiRating($$parsedSource as Partial<BangumiRating>);
    }
}

/**
 * BangumiSubject Bangumi 条目。
 */
export class BangumiSubject {
    "id": number;
    "type": number;
    "name": string;
    "name_cn": string;
    "summary": string;
    "series": boolean;
    "nsfw": boolean;
    "locked": boolean;

    /**
     * YYYY-MM-DD
     */
    "date": string;

    /**
     * TV, Web, 欧美剧...
     */
    "platform": string;
    "images": BangumiImages | null;
    "volumes": number;
    "eps": number;
    "total_episodes": number;
    "rating": BangumiRating | null;
    "collection": BangumiCollection | null;
    "meta_tags": string[];
    "tags": BangumiTag[];

    /** Creates a new BangumiSubject instance. */
    constructor($$source: Partial<BangumiSubject> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("type" in $$source)) {
            this["type"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("name_cn" in $$source)) {
            this["name_cn"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("series" in $$source)) {
            this["series"] = false;
        }
        if (!("nsfw" in $$source)) {
            this["nsfw"] = false;
        }
        if (!("locked" in $$source)) {
            this["locked"] = false;
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("images" in $$source)) {
            this["images"] = null;
        }
        if (!("volumes" in $$source)) {
            this["volumes"] = 0;
        }
        if (!("eps" in $$source)) {
            this["eps"] = 0;
        }
        if (!("total_episodes" in $$source)) {
            this["total_episodes"] = 0;
        }
        if (!("rating" in $$source)) {
            this["rating"] = null;
        }
        if (!("collection" in $$source)) {
            this["collection"] = null;
        }
        if (!("meta_tags" in $$source)) {
            this["meta_tags"] = [];
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BangumiSubject instance from a string or object.
     */
    static createFrom($$source: any = {}): BangumiSubject {
        const $$createField10_0 = $$createType6;
        const $$createField14_0 = $$createType8;
        const $$createField15_0 = $$createType10;
        const $$createField16_0 = $$createType11;
        const $$createField17_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField10_0($$parsedSource["images"]);
        }
        if ("rating" in $$parsedSource) {
            $$parsedSource["rating"] = $$createField14_0($$parsedSource["rating"]);
        }
        if ("collection" in $$parsedSource) {
            $$parsedSource["collection"] = $$createField15_0($$parsedSource["collection"]);
        }
        if ("meta_tags" in $$parsedSource) {
            $$parsedSource["meta_tags"] = $$createField16_0($$parsedSource["meta_tags"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField17_0($$parsedSource["tags"]);
        }
        return new BangumiSubject($$parsedSource as Partial<BangumiSubject>);
    }
}

/**
 * BangumiSubjectType 条目类型枚举。
 * 1=书籍 2=动画 3=音乐 4=游戏 6=三次元（没有 5）。
 */
export enum BangumiSubjectType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    BangumiSubjectBook = 1,
    BangumiSubjectAnime = 2,
    BangumiSubjectMusic = 3,
    BangumiSubjectGame = 4,
    BangumiSubjectReal = 6,
};

/**
 * BangumiTag 条目标签。
 */
export class BangumiTag {
    "name": string;
    "count": number;

    /** Creates a new BangumiTag instance. */
    constructor($$source: Partial<BangumiTag> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BangumiTag instance from a string or object.
     */
    static createFrom($$source: any = {}): BangumiTag {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BangumiTag($$parsedSource as Partial<BangumiTag>);
    }
}

/**
 * BaseInfo 视频基本信息聚合数据。
 * 一次请求返回分类、语种、标签三组下拉选项，供新建视频源表单使用。
 */
export class BaseInfo {
    /**
     * 分类列表
     */
    "categories": VideoCategory[];

    /**
     * 语种列表
     */
    "languages": VideoLanguage[];

    /**
     * 标签列表
     */
    "tags": VideoTag[];

    /** Creates a new BaseInfo instance. */
    constructor($$source: Partial<BaseInfo> = {}) {
        if (!("categories" in $$source)) {
            this["categories"] = [];
        }
        if (!("languages" in $$source)) {
            this["languages"] = [];
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BaseInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BaseInfo {
        const $$createField0_0 = $$createType15;
        const $$createField1_0 = $$createType17;
        const $$createField2_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("categories" in $$parsedSource) {
            $$parsedSource["categories"] = $$createField0_0($$parsedSource["categories"]);
        }
        if ("languages" in $$parsedSource) {
            $$parsedSource["languages"] = $$createField1_0($$parsedSource["languages"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        return new BaseInfo($$parsedSource as Partial<BaseInfo>);
    }
}

/**
 * CreateVideoRepoRequest 新建视频源信息请求体。
 * 字段名直接使用数据库列名，后端直接消费。
 */
export class CreateVideoRepoRequest {
    /**
     * 视频标题（必填）
     */
    "vr_name": string;

    /**
     * 分类（必填，枚举：anime/movie/tv/ova/special）
     */
    "vr_category": string;

    /**
     * 简介（可选）
     */
    "vr_desc": string;

    /**
     * 封面图相对路径（可选，由 /resource/upload 返回）
     */
    "vr_cover": string;

    /**
     * 集数（可选，0 表示未知/连载中）
     */
    "vr_episode_count": number;

    /**
     * 年份（可选，0 表示不筛选）
     */
    "vr_year": number;

    /**
     * 季度（可选，枚举：winter/spring/summer/autumn）
     */
    "vr_season": string;

    /**
     * 状态（可选，默认 3=连载中）
     */
    "vr_status": number;

    /**
     * 语种 ID（可选）
     */
    "vr_language": number;

    /**
     * bangumi 条目 ID（可选，0 表示未关联）
     */
    "vr_bgm_id": number;

    /**
     * 标签 ID 数组（可选）
     */
    "tags": number[];

    /** Creates a new CreateVideoRepoRequest instance. */
    constructor($$source: Partial<CreateVideoRepoRequest> = {}) {
        if (!("vr_name" in $$source)) {
            this["vr_name"] = "";
        }
        if (!("vr_category" in $$source)) {
            this["vr_category"] = "";
        }
        if (!("vr_desc" in $$source)) {
            this["vr_desc"] = "";
        }
        if (!("vr_cover" in $$source)) {
            this["vr_cover"] = "";
        }
        if (!("vr_episode_count" in $$source)) {
            this["vr_episode_count"] = 0;
        }
        if (!("vr_year" in $$source)) {
            this["vr_year"] = 0;
        }
        if (!("vr_season" in $$source)) {
            this["vr_season"] = "";
        }
        if (!("vr_status" in $$source)) {
            this["vr_status"] = 0;
        }
        if (!("vr_language" in $$source)) {
            this["vr_language"] = 0;
        }
        if (!("vr_bgm_id" in $$source)) {
            this["vr_bgm_id"] = 0;
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateVideoRepoRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateVideoRepoRequest {
        const $$createField10_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField10_0($$parsedSource["tags"]);
        }
        return new CreateVideoRepoRequest($$parsedSource as Partial<CreateVideoRepoRequest>);
    }
}

/**
 * CreateVideoRepoResponse 新建视频源信息响应。
 */
export class CreateVideoRepoResponse {
    /**
     * 新建视频的唯一标识
     */
    "vr_id": number;

    /** Creates a new CreateVideoRepoResponse instance. */
    constructor($$source: Partial<CreateVideoRepoResponse> = {}) {
        if (!("vr_id" in $$source)) {
            this["vr_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateVideoRepoResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateVideoRepoResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateVideoRepoResponse($$parsedSource as Partial<CreateVideoRepoResponse>);
    }
}

/**
 * DanmakuItem 弹幕项。
 */
export class DanmakuItem {
    /**
     * 弹幕唯一标识
     */
    "vd_id": number;

    /**
     * 弹幕内容
     */
    "vd_content": string;

    /**
     * 出现时间（毫秒）
     */
    "vd_time": number;

    /**
     * 类型：1=滚动，2=顶部，3=底部
     */
    "vd_mode": number;

    /**
     * 颜色（#RRGGBB）
     */
    "vd_color": string;

    /** Creates a new DanmakuItem instance. */
    constructor($$source: Partial<DanmakuItem> = {}) {
        if (!("vd_id" in $$source)) {
            this["vd_id"] = 0;
        }
        if (!("vd_content" in $$source)) {
            this["vd_content"] = "";
        }
        if (!("vd_time" in $$source)) {
            this["vd_time"] = 0;
        }
        if (!("vd_mode" in $$source)) {
            this["vd_mode"] = 0;
        }
        if (!("vd_color" in $$source)) {
            this["vd_color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DanmakuItem instance from a string or object.
     */
    static createFrom($$source: any = {}): DanmakuItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DanmakuItem($$parsedSource as Partial<DanmakuItem>);
    }
}

/**
 * DanmakuPostRequest 发送弹幕请求体。
 */
export class DanmakuPostRequest {
    /**
     * 分集 ID
     */
    "ve_id": number;

    /**
     * 弹幕内容（1-100 字）
     */
    "vd_content": string;

    /**
     * 出现时间（毫秒）
     */
    "vd_time": number;

    /**
     * 类型：1=滚动，2=顶部，3=底部
     */
    "vd_mode": number;

    /**
     * 颜色（#RRGGBB）
     */
    "vd_color": string;

    /** Creates a new DanmakuPostRequest instance. */
    constructor($$source: Partial<DanmakuPostRequest> = {}) {
        if (!("ve_id" in $$source)) {
            this["ve_id"] = 0;
        }
        if (!("vd_content" in $$source)) {
            this["vd_content"] = "";
        }
        if (!("vd_time" in $$source)) {
            this["vd_time"] = 0;
        }
        if (!("vd_mode" in $$source)) {
            this["vd_mode"] = 0;
        }
        if (!("vd_color" in $$source)) {
            this["vd_color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DanmakuPostRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DanmakuPostRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DanmakuPostRequest($$parsedSource as Partial<DanmakuPostRequest>);
    }
}

/**
 * DiscussItem 评论项。
 */
export class DiscussItem {
    /**
     * 评论唯一标识
     */
    "vrd_id": number;

    /**
     * 评论内容
     */
    "vrd_content": string;

    /**
     * 回复数（仅顶级评论返回，回复固定为 0）
     */
    "reply_count": number;

    /**
     * 创建时间（秒级时间戳）
     */
    "create_time": number;

    /**
     * 预览回复（仅顶级评论返回，最多 3 条，最早在前）
     */
    "replies": (DiscussItem | null)[];

    /** Creates a new DiscussItem instance. */
    constructor($$source: Partial<DiscussItem> = {}) {
        if (!("vrd_id" in $$source)) {
            this["vrd_id"] = 0;
        }
        if (!("vrd_content" in $$source)) {
            this["vrd_content"] = "";
        }
        if (!("reply_count" in $$source)) {
            this["reply_count"] = 0;
        }
        if (!("create_time" in $$source)) {
            this["create_time"] = 0;
        }
        if (!("replies" in $$source)) {
            this["replies"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscussItem instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscussItem {
        const $$createField4_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("replies" in $$parsedSource) {
            $$parsedSource["replies"] = $$createField4_0($$parsedSource["replies"]);
        }
        return new DiscussItem($$parsedSource as Partial<DiscussItem>);
    }
}

/**
 * DiscussPostRequest 发表评论请求体。
 */
export class DiscussPostRequest {
    /**
     * 分集 ID
     */
    "ve_id": number;

    /**
     * 评论内容（1-500 字）
     */
    "vrd_content": string;

    /**
     * 父评论 ID（0 表示顶级评论）
     */
    "parent_id": number;

    /** Creates a new DiscussPostRequest instance. */
    constructor($$source: Partial<DiscussPostRequest> = {}) {
        if (!("ve_id" in $$source)) {
            this["ve_id"] = 0;
        }
        if (!("vrd_content" in $$source)) {
            this["vrd_content"] = "";
        }
        if (!("parent_id" in $$source)) {
            this["parent_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscussPostRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscussPostRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscussPostRequest($$parsedSource as Partial<DiscussPostRequest>);
    }
}

/**
 * EpisodeItem 分集项。
 */
export class EpisodeItem {
    /**
     * 分集唯一标识
     */
    "ve_id": number;

    /**
     * 频道 ID（TG peer_id，客户端回源拉流用）
     */
    "vs_channel_id": number;

    /**
     * TG 消息 ID（客户端回源拉流用）
     */
    "ve_message_id": number;

    /**
     * 分集标题
     */
    "ve_title": string;

    /**
     * 集数（0 表示未识别）
     */
    "ve_collect": number;

    /**
     * 状态：1=正常，2=失效
     */
    "ve_status": number;

    /** Creates a new EpisodeItem instance. */
    constructor($$source: Partial<EpisodeItem> = {}) {
        if (!("ve_id" in $$source)) {
            this["ve_id"] = 0;
        }
        if (!("vs_channel_id" in $$source)) {
            this["vs_channel_id"] = 0;
        }
        if (!("ve_message_id" in $$source)) {
            this["ve_message_id"] = 0;
        }
        if (!("ve_title" in $$source)) {
            this["ve_title"] = "";
        }
        if (!("ve_collect" in $$source)) {
            this["ve_collect"] = 0;
        }
        if (!("ve_status" in $$source)) {
            this["ve_status"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EpisodeItem instance from a string or object.
     */
    static createFrom($$source: any = {}): EpisodeItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EpisodeItem($$parsedSource as Partial<EpisodeItem>);
    }
}

/**
 * EpisodeUploadItem 单条分集上传项。
 */
export class EpisodeUploadItem {
    /**
     * 频道 ID（TG peer_id）
     */
    "vs_channel_id": number;

    /**
     * TG 消息 ID
     */
    "ve_message_id": number;

    /**
     * 分集标题
     */
    "ve_title": string;

    /**
     * 集数（0 表示未识别）
     */
    "ve_collect": number;

    /** Creates a new EpisodeUploadItem instance. */
    constructor($$source: Partial<EpisodeUploadItem> = {}) {
        if (!("vs_channel_id" in $$source)) {
            this["vs_channel_id"] = 0;
        }
        if (!("ve_message_id" in $$source)) {
            this["ve_message_id"] = 0;
        }
        if (!("ve_title" in $$source)) {
            this["ve_title"] = "";
        }
        if (!("ve_collect" in $$source)) {
            this["ve_collect"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EpisodeUploadItem instance from a string or object.
     */
    static createFrom($$source: any = {}): EpisodeUploadItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EpisodeUploadItem($$parsedSource as Partial<EpisodeUploadItem>);
    }
}

/**
 * HistoryListItem 最近观看列表项。
 */
export class HistoryListItem {
    /**
     * 视频 ID
     */
    "vr_id": number;

    /**
     * 最后观看的分集 ID
     */
    "ve_id": number;

    /**
     * 播放进度（秒），0=已看完
     */
    "vuh_history_time": number;

    /**
     * 最后观看时间（秒级时间戳）
     */
    "update_time": number;

    /**
     * 视频标题
     */
    "vr_name": string;

    /**
     * 封面图（相对路径，前端拼接 CDN）
     */
    "vr_cover": string;

    /**
     * 集数（0 表示未知/连载中）
     */
    "vr_episode_count": number;

    /**
     * 最后观看的分集集数
     */
    "ve_collect": number;

    /** Creates a new HistoryListItem instance. */
    constructor($$source: Partial<HistoryListItem> = {}) {
        if (!("vr_id" in $$source)) {
            this["vr_id"] = 0;
        }
        if (!("ve_id" in $$source)) {
            this["ve_id"] = 0;
        }
        if (!("vuh_history_time" in $$source)) {
            this["vuh_history_time"] = 0;
        }
        if (!("update_time" in $$source)) {
            this["update_time"] = 0;
        }
        if (!("vr_name" in $$source)) {
            this["vr_name"] = "";
        }
        if (!("vr_cover" in $$source)) {
            this["vr_cover"] = "";
        }
        if (!("vr_episode_count" in $$source)) {
            this["vr_episode_count"] = 0;
        }
        if (!("ve_collect" in $$source)) {
            this["ve_collect"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryListItem instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryListItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryListItem($$parsedSource as Partial<HistoryListItem>);
    }
}

/**
 * HistoryProgress 播放进度。
 */
export class HistoryProgress {
    /**
     * 上次播放位置（秒），0=无记录或已看完
     */
    "vuh_history_time": number;

    /** Creates a new HistoryProgress instance. */
    constructor($$source: Partial<HistoryProgress> = {}) {
        if (!("vuh_history_time" in $$source)) {
            this["vuh_history_time"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryProgress($$parsedSource as Partial<HistoryProgress>);
    }
}

/**
 * HistoryReportRequest 上报播放进度请求体。
 */
export class HistoryReportRequest {
    /**
     * 视频 ID
     */
    "vr_id": number;

    /**
     * 分集 ID
     */
    "ve_id": number;

    /**
     * 续播进度（秒），看完时传 0
     */
    "vuh_history_time": number;

    /**
     * 实际观看时长（秒），看完时传视频总时长
     */
    "vuh_duration": number;

    /**
     * 是否看完（0/1），看完时传 1
     */
    "finished": number;

    /** Creates a new HistoryReportRequest instance. */
    constructor($$source: Partial<HistoryReportRequest> = {}) {
        if (!("vr_id" in $$source)) {
            this["vr_id"] = 0;
        }
        if (!("ve_id" in $$source)) {
            this["ve_id"] = 0;
        }
        if (!("vuh_history_time" in $$source)) {
            this["vuh_history_time"] = 0;
        }
        if (!("vuh_duration" in $$source)) {
            this["vuh_duration"] = 0;
        }
        if (!("finished" in $$source)) {
            this["finished"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryReportRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryReportRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryReportRequest($$parsedSource as Partial<HistoryReportRequest>);
    }
}

/**
 * HomeBannerItem 首页横幅项。横幅封面取自 video_banner.vb_cover（与 latest/hot 的 vr_cover 不同）。
 */
export class HomeBannerItem {
    /**
     * 视频唯一标识
     */
    "vr_id": number;

    /**
     * 视频标题
     */
    "vr_name": string;

    /**
     * 横幅封面（相对路径，前端自行拼接 CDN）
     */
    "vb_cover": string;

    /**
     * 集数（如 12；0 表示未知/连载中）
     */
    "vr_episode_count": number;

    /** Creates a new HomeBannerItem instance. */
    constructor($$source: Partial<HomeBannerItem> = {}) {
        if (!("vr_id" in $$source)) {
            this["vr_id"] = 0;
        }
        if (!("vr_name" in $$source)) {
            this["vr_name"] = "";
        }
        if (!("vb_cover" in $$source)) {
            this["vb_cover"] = "";
        }
        if (!("vr_episode_count" in $$source)) {
            this["vr_episode_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HomeBannerItem instance from a string or object.
     */
    static createFrom($$source: any = {}): HomeBannerItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HomeBannerItem($$parsedSource as Partial<HomeBannerItem>);
    }
}

/**
 * HomeData 首页聚合数据，包含 Banner、最新上架、热门播放三个板块。
 */
export class HomeData {
    /**
     * Banner 轮播（3-5 张推荐位，横幅封面取自 video_banner.vb_cover）
     */
    "banner": HomeBannerItem[];

    /**
     * 最新上架（按发布时间倒序）
     */
    "latest": HomeVideoItem[];

    /**
     * 热门播放（单一榜单，按播放量排序）
     */
    "hot": HomeVideoItem[];

    /** Creates a new HomeData instance. */
    constructor($$source: Partial<HomeData> = {}) {
        if (!("banner" in $$source)) {
            this["banner"] = [];
        }
        if (!("latest" in $$source)) {
            this["latest"] = [];
        }
        if (!("hot" in $$source)) {
            this["hot"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HomeData instance from a string or object.
     */
    static createFrom($$source: any = {}): HomeData {
        const $$createField0_0 = $$createType25;
        const $$createField1_0 = $$createType27;
        const $$createField2_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("banner" in $$parsedSource) {
            $$parsedSource["banner"] = $$createField0_0($$parsedSource["banner"]);
        }
        if ("latest" in $$parsedSource) {
            $$parsedSource["latest"] = $$createField1_0($$parsedSource["latest"]);
        }
        if ("hot" in $$parsedSource) {
            $$parsedSource["hot"] = $$createField2_0($$parsedSource["hot"]);
        }
        return new HomeData($$parsedSource as Partial<HomeData>);
    }
}

/**
 * HomeVideoItem 首页视频项。
 */
export class HomeVideoItem {
    /**
     * 视频唯一标识
     */
    "vr_id": number;

    /**
     * 视频标题
     */
    "vr_name": string;

    /**
     * 封面图（相对路径，前端自行拼接 CDN）
     */
    "vr_cover": string;

    /**
     * 集数（如 12；0 表示未知/连载中）
     */
    "vr_episode_count": number;

    /** Creates a new HomeVideoItem instance. */
    constructor($$source: Partial<HomeVideoItem> = {}) {
        if (!("vr_id" in $$source)) {
            this["vr_id"] = 0;
        }
        if (!("vr_name" in $$source)) {
            this["vr_name"] = "";
        }
        if (!("vr_cover" in $$source)) {
            this["vr_cover"] = "";
        }
        if (!("vr_episode_count" in $$source)) {
            this["vr_episode_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HomeVideoItem instance from a string or object.
     */
    static createFrom($$source: any = {}): HomeVideoItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HomeVideoItem($$parsedSource as Partial<HomeVideoItem>);
    }
}

/**
 * ListDiscussRequest 评论列表游标分页请求。
 */
export class ListDiscussRequest {
    /**
     * 分集 ID
     */
    "ve_id": number;

    /**
     * 父评论 ID（0=顶级评论）
     */
    "parent_id": number;

    /**
     * 排序：latest（默认）/ hot，仅顶级评论生效
     */
    "sort": string;

    /**
     * 游标 vrd_id，0=第一页
     */
    "cursor_vrd_id": number;

    /**
     * 每页条数，默认 20，最大 50
     */
    "limit": number;

    /** Creates a new ListDiscussRequest instance. */
    constructor($$source: Partial<ListDiscussRequest> = {}) {
        if (!("ve_id" in $$source)) {
            this["ve_id"] = 0;
        }
        if (!("parent_id" in $$source)) {
            this["parent_id"] = 0;
        }
        if (!("sort" in $$source)) {
            this["sort"] = "";
        }
        if (!("cursor_vrd_id" in $$source)) {
            this["cursor_vrd_id"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListDiscussRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ListDiscussRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListDiscussRequest($$parsedSource as Partial<ListDiscussRequest>);
    }
}

/**
 * SearchRequest 分类检索查询参数。
 * 通过 JSON body 提交到 POST /video/repo/search。
 */
export class SearchRequest {
    /**
     * 分类：anime/movie/tv/ova/special，空表示全部
     */
    "category": string;

    /**
     * 标签 ID 数组，空表示不筛选
     */
    "tags": number[];

    /**
     * 年份（如 2025），0 表示不筛选
     */
    "year": number;

    /**
     * 季度：winter/spring/summer/autumn，空表示不筛选
     */
    "season": string;

    /**
     * 排序：latest/hot，空默认 latest
     */
    "sort": string;

    /**
     * 标题关键词（服务器端模糊匹配），空表示不搜索
     */
    "keyword": string;

    /**
     * 页码（从 1 开始），0 默认 1
     */
    "page": number;

    /**
     * 每页数量（≤50），0 默认 20
     */
    "page_size": number;

    /** Creates a new SearchRequest instance. */
    constructor($$source: Partial<SearchRequest> = {}) {
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("year" in $$source)) {
            this["year"] = 0;
        }
        if (!("season" in $$source)) {
            this["season"] = "";
        }
        if (!("sort" in $$source)) {
            this["sort"] = "";
        }
        if (!("keyword" in $$source)) {
            this["keyword"] = "";
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            this["page_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchRequest {
        const $$createField1_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField1_0($$parsedSource["tags"]);
        }
        return new SearchRequest($$parsedSource as Partial<SearchRequest>);
    }
}

/**
 * SearchResult 分类检索结果，包含列表数据与分页信息。
 */
export class SearchResult {
    /**
     * 当前页数据
     */
    "list": VideoSearchItem[];

    /**
     * 总条数（用于分页）
     */
    "total": number;

    /**
     * 当前页码
     */
    "page": number;

    /**
     * 每页数量
     */
    "page_size": number;

    /**
     * 是否有下一页
     */
    "has_more": boolean;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("list" in $$source)) {
            this["list"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            this["page_size"] = 0;
        }
        if (!("has_more" in $$source)) {
            this["has_more"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        const $$createField0_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("list" in $$parsedSource) {
            $$parsedSource["list"] = $$createField0_0($$parsedSource["list"]);
        }
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

/**
 * UploadEpisodesRequest 批量上传分集请求体。
 */
export class UploadEpisodesRequest {
    /**
     * 视频ID
     */
    "vr_id": number;

    /**
     * 分集列表
     */
    "episodes": EpisodeUploadItem[];

    /** Creates a new UploadEpisodesRequest instance. */
    constructor($$source: Partial<UploadEpisodesRequest> = {}) {
        if (!("vr_id" in $$source)) {
            this["vr_id"] = 0;
        }
        if (!("episodes" in $$source)) {
            this["episodes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadEpisodesRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadEpisodesRequest {
        const $$createField1_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("episodes" in $$parsedSource) {
            $$parsedSource["episodes"] = $$createField1_0($$parsedSource["episodes"]);
        }
        return new UploadEpisodesRequest($$parsedSource as Partial<UploadEpisodesRequest>);
    }
}

/**
 * UploadEpisodesResponse 批量上传分集响应。
 * 后端仅返回成功/失败，不返回分集列表。
 */
export class UploadEpisodesResponse {

    /** Creates a new UploadEpisodesResponse instance. */
    constructor($$source: Partial<UploadEpisodesResponse> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadEpisodesResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadEpisodesResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadEpisodesResponse($$parsedSource as Partial<UploadEpisodesResponse>);
    }
}

/**
 * UserInfo 用户信息响应。
 * 本地单机模式无用户体系，结构体保留为空，GetUserInfo 返回空对象。
 */
export class UserInfo {

    /** Creates a new UserInfo instance. */
    constructor($$source: Partial<UserInfo> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UserInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserInfo($$parsedSource as Partial<UserInfo>);
    }
}

/**
 * VideoCategory 视频分类项。
 */
export class VideoCategory {
    /**
     * 分类 ID
     */
    "vc_id": number;

    /**
     * 分类名称
     */
    "vc_name": string;

    /** Creates a new VideoCategory instance. */
    constructor($$source: Partial<VideoCategory> = {}) {
        if (!("vc_id" in $$source)) {
            this["vc_id"] = 0;
        }
        if (!("vc_name" in $$source)) {
            this["vc_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoCategory instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoCategory {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoCategory($$parsedSource as Partial<VideoCategory>);
    }
}

/**
 * VideoDetail 视频简介详情。
 */
export class VideoDetail {
    /**
     * 视频ID
     */
    "vr_id": number;

    /**
     * 视频标题
     */
    "vr_name": string;

    /**
     * 描述
     */
    "vr_desc": string;

    /**
     * 封面图相对路径
     */
    "vr_cover": string;

    /**
     * 分类
     */
    "vr_category": string;

    /**
     * 集数（0 表示未知/连载中）
     */
    "vr_episode_count": number;

    /**
     * 当前更新集数
     */
    "vr_now_count": number;

    /**
     * 年份
     */
    "vr_year": number;

    /**
     * 季度
     */
    "vr_season": string;

    /**
     * 总播放量
     */
    "vr_view_count": number;

    /**
     * 状态：1=完结，2=停更，3=连载中
     */
    "vr_status": number;

    /**
     * 语种 ID
     */
    "vr_language": number;

    /**
     * bangumi 条目 ID（0 表示未关联）
     */
    "vr_bgm_id": number;

    /**
     * 更新时间（秒级时间戳）
     */
    "update_time": number;

    /**
     * 当前用户是否已追番
     */
    "is_followed": boolean;

    /** Creates a new VideoDetail instance. */
    constructor($$source: Partial<VideoDetail> = {}) {
        if (!("vr_id" in $$source)) {
            this["vr_id"] = 0;
        }
        if (!("vr_name" in $$source)) {
            this["vr_name"] = "";
        }
        if (!("vr_desc" in $$source)) {
            this["vr_desc"] = "";
        }
        if (!("vr_cover" in $$source)) {
            this["vr_cover"] = "";
        }
        if (!("vr_category" in $$source)) {
            this["vr_category"] = "";
        }
        if (!("vr_episode_count" in $$source)) {
            this["vr_episode_count"] = 0;
        }
        if (!("vr_now_count" in $$source)) {
            this["vr_now_count"] = 0;
        }
        if (!("vr_year" in $$source)) {
            this["vr_year"] = 0;
        }
        if (!("vr_season" in $$source)) {
            this["vr_season"] = "";
        }
        if (!("vr_view_count" in $$source)) {
            this["vr_view_count"] = 0;
        }
        if (!("vr_status" in $$source)) {
            this["vr_status"] = 0;
        }
        if (!("vr_language" in $$source)) {
            this["vr_language"] = 0;
        }
        if (!("vr_bgm_id" in $$source)) {
            this["vr_bgm_id"] = 0;
        }
        if (!("update_time" in $$source)) {
            this["update_time"] = 0;
        }
        if (!("is_followed" in $$source)) {
            this["is_followed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoDetail($$parsedSource as Partial<VideoDetail>);
    }
}

/**
 * VideoFollowRequest 视频追番请求体（toggle 语义）。
 */
export class VideoFollowRequest {
    /**
     * 视频 ID
     */
    "vr_id": number;

    /** Creates a new VideoFollowRequest instance. */
    constructor($$source: Partial<VideoFollowRequest> = {}) {
        if (!("vr_id" in $$source)) {
            this["vr_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoFollowRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoFollowRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoFollowRequest($$parsedSource as Partial<VideoFollowRequest>);
    }
}

/**
 * VideoFollowResponse 视频追番响应。
 */
export class VideoFollowResponse {
    /**
     * 操作后的追番状态
     */
    "is_followed": boolean;

    /**
     * 操作后的追番数
     */
    "follow_count": number;

    /** Creates a new VideoFollowResponse instance. */
    constructor($$source: Partial<VideoFollowResponse> = {}) {
        if (!("is_followed" in $$source)) {
            this["is_followed"] = false;
        }
        if (!("follow_count" in $$source)) {
            this["follow_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoFollowResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoFollowResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoFollowResponse($$parsedSource as Partial<VideoFollowResponse>);
    }
}

/**
 * VideoLanguage 视频语种项。
 */
export class VideoLanguage {
    /**
     * 语种 ID
     */
    "vl_id": number;

    /**
     * 语种名称
     */
    "vl_name": string;

    /** Creates a new VideoLanguage instance. */
    constructor($$source: Partial<VideoLanguage> = {}) {
        if (!("vl_id" in $$source)) {
            this["vl_id"] = 0;
        }
        if (!("vl_name" in $$source)) {
            this["vl_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoLanguage instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoLanguage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoLanguage($$parsedSource as Partial<VideoLanguage>);
    }
}

/**
 * VideoSearchItem 视频检索项。
 */
export class VideoSearchItem {
    /**
     * 视频唯一标识
     */
    "vr_id": number;

    /**
     * 视频标题
     */
    "vr_name": string;

    /**
     * 封面图（相对路径，前端自行拼接 CDN）
     */
    "vr_cover": string;

    /**
     * 集数
     */
    "vr_episode_count": number;

    /**
     * 分类
     */
    "vr_category": string;

    /**
     * 年份
     */
    "vr_year": number;

    /**
     * 季度
     */
    "vr_season": string;

    /**
     * 播放量
     */
    "vr_view_count": number;

    /**
     * bangumi 条目 ID（0 表示未关联）
     */
    "vr_bgm_id": number;

    /**
     * 更新时间（秒级时间戳）
     */
    "update_time": number;

    /** Creates a new VideoSearchItem instance. */
    constructor($$source: Partial<VideoSearchItem> = {}) {
        if (!("vr_id" in $$source)) {
            this["vr_id"] = 0;
        }
        if (!("vr_name" in $$source)) {
            this["vr_name"] = "";
        }
        if (!("vr_cover" in $$source)) {
            this["vr_cover"] = "";
        }
        if (!("vr_episode_count" in $$source)) {
            this["vr_episode_count"] = 0;
        }
        if (!("vr_category" in $$source)) {
            this["vr_category"] = "";
        }
        if (!("vr_year" in $$source)) {
            this["vr_year"] = 0;
        }
        if (!("vr_season" in $$source)) {
            this["vr_season"] = "";
        }
        if (!("vr_view_count" in $$source)) {
            this["vr_view_count"] = 0;
        }
        if (!("vr_bgm_id" in $$source)) {
            this["vr_bgm_id"] = 0;
        }
        if (!("update_time" in $$source)) {
            this["update_time"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoSearchItem instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoSearchItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoSearchItem($$parsedSource as Partial<VideoSearchItem>);
    }
}

/**
 * VideoTag 视频标签项。
 */
export class VideoTag {
    /**
     * 标签 ID
     */
    "vt_id": number;

    /**
     * 标签名称
     */
    "vt_name": string;

    /** Creates a new VideoTag instance. */
    constructor($$source: Partial<VideoTag> = {}) {
        if (!("vt_id" in $$source)) {
            this["vt_id"] = 0;
        }
        if (!("vt_name" in $$source)) {
            this["vt_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoTag instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoTag {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoTag($$parsedSource as Partial<VideoTag>);
    }
}

// Private type creation functions
const $$createType0 = BangumiEpisode.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = BangumiSubject.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = BangumiImages.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = BangumiRating.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = BangumiCollection.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $Create.Array($Create.Any);
const $$createType12 = BangumiTag.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = VideoCategory.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = VideoLanguage.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = VideoTag.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $Create.Array($Create.Any);
const $$createType21 = DiscussItem.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = HomeBannerItem.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = HomeVideoItem.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = VideoSearchItem.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = EpisodeUploadItem.createFrom;
const $$createType31 = $Create.Array($$createType30);
